__doc__='''
This module include mapping required by the workflow.
------------------------------------------------------------
(MAP) Resi_map
Map residue key with the 3 letter name.
{resi_key:resi_name_3,...}
------------------------------------------------------------
(MAP) Resi_map2
Map 3 letter name with residue key.
{resi_name_3:resi_key,...}
------------------------------------------------------------
(List) Resi_list
Map residue key with index number
[resi_key,...]
------------------------------------------------------------
(???) Atom_topology


------------------------------------------------------------
'''

Resi_map={'R':'ARG',
          'H':'HIS',
          'K':'LYS',
          'D':'ASP',
          'E':'GLU',
          'S':'SER',
          'T':'THR',
          'N':'ASN',
          'Q':'GLN',
          'C':'CYS',
          'U':'SEC',
          'G':'GLY',
          'P':'PRO',
          'A':'ALA',
          'V':'VAL',
          'I':'ILE',
          'L':'LEU',
          'M':'MET',
          'F':'PHE',
          'Y':'TYR',
          'W':'TRP'}

Resi_map2={'ARG':'R',
           'HIS':'H',
           'HIE':'H',
           'HIP':'H',
           'HID':'H',
           'LYS':'K',
           'ASP':'D',
           'GLU':'E',
           'SER':'S',
           'THR':'T',
           'ASN':'N',
           'GLN':'Q',
           'CYS':'C',
           'SEC':'U',
           'GLY':'G',
           'PRO':'P',
           'ALA':'A',
           'VAL':'V',
           'ILE':'I',
           'LEU':'L',
           'MET':'M',
           'PHE':'F',
           'TYR':'Y',
           'TRP':'W'}

Resi_list=['R','H','K','D','E','S','T','N','Q','C','U','G','P','A','V','I','L','M','F','Y','W']

TIP3P_map=[ "O" , "H" , "OW", "HW","HOH","WAT",
            "F" , 
	        "Cl", "CL",
	        "Br", "BR",
	        "I" ,
	        "Li", "LI",
	        "Na", "NA",
            "K" ,
	        "Rb", "RB",
	        "Cs", "CS",
	        "Mg", "MG",
            "Tl", "TL",
            "Cu", "CU",
            "Ag", "AG",
            "Be", "BE",
            "Ni", "NI",
            "Pt", "PT",
            "Zn", "ZN",
            "Co", "CO",
            "Pd", "PD",
            "Cr", "CR",
            "Fe", "FE",
            "V" ,
            "Mn", "MN",
            "Hg", "HG",
            "Cd", "CD",
            "Yb", "YB",
            "Ca", "CA",
            "Sn", "SN",
            "Pb", "PB",
            "Eu", "EU",
            "Sr", "SR",
            "Sm", "SM",
            "Ba", "BA",
            "Ra", "RA",
            "Al", "AL",
            "In", "IN",
            "Y" ,
            "La", "LA",
            "Ce", "CE",
            "Pr", "PR",
            "Nd", "ND",
            "Gd", "GD",
            "Tb", "TB",
            "Dy", "DY",
            "Er", "ER",
            "Tm", "TM",
            "Lu", "LU",
            "Hf", "HF",
            "Zr", "ZR",
            "U" ,
            "Pu", "PU",
            "Th", "TH"  ]

# a map all metal (resi_name:atom_name)
Metal_map ={"LI" : "Li",
	        "NA" : "Na",
            "K"  : "K" ,
	        "RB" : "Rb",
	        "CS" : "Cs",
	        "MG" : "Mg",
            "TL" : "Tl",
            "CU" : "Cu",
            "AG" : "Ag",
            "BE" : "Be",
            "NI" : "Ni",
            "PT" : "Pt",
            "ZN" : "Zn",
            "CO" : "Co",
            "PD" : "Pd",
            "CR" : "Cr",
            "FE" : "Fe",
            "V"  : "V" ,
            "MN" : "Mn",
            "HG" : "Hg",
            "CD" : "Cd",
            "YB" : "Yb",
            "CA" : "Ca",
            "SN" : "Sn",
            "PB" : "Pb",
            "EU" : "Eu",
            "SR" : "Sr",
            "SM" : "Sm",
            "BA" : "Ba",
            "RA" : "Ra",
            "AL" : "Al",
            "IN" : "In",
            "Y"  : "Y" ,
            "LA" : "La",
            "CE" : "Ce",
            "PR" : "Pr",
            "ND" : "Nd",
            "GD" : "Gd",
            "TB" : "Tb",
            "DY" : "Dy",
            "ER" : "Er",
            "TM" : "Tm",
            "LU" : "Lu",
            "HF" : "Hf",
            "ZR" : "Zr",
            "U"  : "U" ,
            "PU" : "Pu",
            "TH" : "Th" }

# Potential coordination center: add upon discover. (resi_name:atom_name)
MetalCenter_map = { "MG" : "Mg",
                    "TL" : "Tl",
                    "CU" : "Cu",
                    "AG" : "Ag",
                    "BE" : "Be",
                    "NI" : "Ni",
                    "PT" : "Pt",
                    "ZN" : "Zn",
                    "CO" : "Co",
                    "PD" : "Pd",
                    "CR" : "Cr",
                    "FE" : "Fe",
                    "V"  : "V" ,
                    "MN" : "Mn",
                    "HG" : "Hg",
                    "CD" : "Cd",
                    "YB" : "Yb",
                    "CA" : "Ca",
                    "SN" : "Sn",
                    "PB" : "Pb",
                    "EU" : "Eu",
                    "SR" : "Sr",
                    "SM" : "Sm",
                    "BA" : "Ba",
                    "RA" : "Ra",
                    "AL" : "Al",
                    "IN" : "In",
                    "Y"  : "Y" ,
                    "LA" : "La",
                    "CE" : "Ce",
                    "PR" : "Pr",
                    "ND" : "Nd",
                    "GD" : "Gd",
                    "TB" : "Tb",
                    "DY" : "Dy",
                    "ER" : "Er",
                    "TM" : "Tm",
                    "LU" : "Lu",
                    "HF" : "Hf",
                    "ZR" : "Zr",
                    "U"  : "U" ,
                    "PU" : "Pu",
                    "TH" : "Th" }

# Potential coordination donor: add upon discover. (atom_name:element)
Donor_atom_map={"SG" : "S",
                "TL" : "Tl",
                "CU" : "Cu",
                "AG" : "Ag",
                "BE" : "Be",
                "NI" : "Ni",
                "PT" : "Pt",
                "ZN" : "Zn",
                "CO" : "Co",
                "PD" : "Pd",
                "CR" : "Cr",
                "FE" : "Fe",
                "V"  : "V" ,
                "MN" : "Mn",
                "HG" : "Hg",
                "CD" : "Cd",
                "YB" : "Yb",
                "CA" : "Ca",
                "SN" : "Sn",
                "PB" : "Pb",
                "EU" : "Eu",
                "SR" : "Sr",
                "SM" : "Sm",
                "BA" : "Ba",
                "RA" : "Ra",
                "AL" : "Al",
                "IN" : "In",
                "Y"  : "Y" ,
                "LA" : "La",
                "CE" : "Ce",
                "PR" : "Pr",
                "ND" : "Nd",
                "GD" : "Gd",
                "TB" : "Tb",
                "DY" : "Dy",
                "ER" : "Er",
                "TM" : "Tm",
                "LU" : "Lu",
                "HF" : "Hf",
                "ZR" : "Zr",
                "U"  : "U" ,
                "PU" : "Pu",
                "TH" : "Th" }


# reference: doi:10.1107/S0567739476001551 (element : radius)
Ionic_radious_map={ "Li" : None, 
                    "Na" : None, 
                    "K"  : None, 
                    "Rb" : None, 
                    "Cs" : None, 
                    "Mg" : None, 
                    "Tl" : None, 
                    "Cu" : None, 
                    "Ag" : None, 
                    "Be" : None, 
                    "Ni" : None, 
                    "Pt" : None, 
                    "Zn" : None, 
                    "Co" : None, 
                    "Pd" : None, 
                    "Cr" : None, 
                    "Fe" : None, 
                    "V"  : None, 
                    "Mn" : None, 
                    "Hg" : None, 
                    "Cd" : None, 
                    "Yb" : None, 
                    "Ca" : None, 
                    "Sn" : None, 
                    "Pb" : None, 
                    "Eu" : None, 
                    "Sr" : None, 
                    "Sm" : None, 
                    "Ba" : None, 
                    "Ra" : None, 
                    "Al" : None, 
                    "In" : None, 
                    "Y"  : None, 
                    "La" : None, 
                    "Ce" : None, 
                    "Pr" : None, 
                    "Nd" : None, 
                    "Gd" : None, 
                    "Tb" : None, 
                    "Dy" : None, 
                    "Er" : None, 
                    "Tm" : None, 
                    "Lu" : None, 
                    "Hf" : None, 
                    "Zr" : None, 
                    "U"  : None, 
                    "Pu" : None, 
                    "Th" : None }

# reference:  doi:10.1021/jp8111556 (element : radius)
VDW_radious_map = { "Li" : None, 
                    "Na" : None, 
                    "K"  : None, 
                    "Rb" : None, 
                    "Cs" : None, 
                    "Mg" : None, 
                    "Tl" : None, 
                    "Cu" : None, 
                    "Ag" : None, 
                    "Be" : None, 
                    "Ni" : None, 
                    "Pt" : None, 
                    "Zn" : None, 
                    "Co" : None, 
                    "Pd" : None, 
                    "Cr" : None, 
                    "Fe" : None, 
                    "V"  : None, 
                    "Mn" : None, 
                    "Hg" : None, 
                    "Cd" : None, 
                    "Yb" : None, 
                    "Ca" : None, 
                    "Sn" : None, 
                    "Pb" : None, 
                    "Eu" : None, 
                    "Sr" : None, 
                    "Sm" : None, 
                    "Ba" : None, 
                    "Ra" : None, 
                    "Al" : None, 
                    "In" : None, 
                    "Y"  : None, 
                    "La" : None, 
                    "Ce" : None, 
                    "Pr" : None, 
                    "Nd" : None, 
                    "Gd" : None, 
                    "Tb" : None, 
                    "Dy" : None, 
                    "Er" : None, 
                    "Tm" : None, 
                    "Lu" : None, 
                    "Hf" : None, 
                    "Zr" : None, 
                    "U"  : None, 
                    "Pu" : None, 
                    "Th" : None }

