__doc__='''
This module include mapping required by the workflow.
------------------------------------------------------------
(MAP) Resi_map
Map residue key with the 3 letter name.
{resi_key:resi_name_3,...}
------------------------------------------------------------
(MAP) Resi_map2
Map 3 letter name with residue key.
{resi_name_3:resi_key,...}
------------------------------------------------------------
(List) Resi_list
Map residue key with index number
[resi_key,...]
------------------------------------------------------------
(???) Atom_topology


------------------------------------------------------------
'''

Resi_map={'R':'ARG',
          'H':'HIS',
          'K':'LYS',
          'D':'ASP',
          'E':'GLU',
          'S':'SER',
          'T':'THR',
          'N':'ASN',
          'Q':'GLN',
          'C':'CYS',
          'U':'SEC',
          'G':'GLY',
          'P':'PRO',
          'A':'ALA',
          'V':'VAL',
          'I':'ILE',
          'L':'LEU',
          'M':'MET',
          'F':'PHE',
          'Y':'TYR',
          'W':'TRP'}

Resi_map2={'ARG':'R',
           'HIS':'H',
           'HIE':'H',
           'HIP':'H',
           'HID':'H',
           'LYS':'K',
           'ASP':'D',
           'GLU':'E',
           'SER':'S',
           'THR':'T',
           'ASN':'N',
           'GLN':'Q',
           'CYS':'C',
           'SEC':'U',
           'GLY':'G',
           'PRO':'P',
           'ALA':'A',
           'VAL':'V',
           'ILE':'I',
           'LEU':'L',
           'MET':'M',
           'PHE':'F',
           'TYR':'Y',
           'TRP':'W'}

Resi_list=['R','H','K','D','E','S','T','N','Q','C','U','G','P','A','V','I','L','M','F','Y','W']

TIP3P_map=[ "O" , "H" , "OW", "HW","HOH","WAT",
            "F" , 
	        "Cl", "CL",
	        "Br", "BR",
	        "I" ,
	        "Li", "LI",
	        "Na", "NA",
            "K" ,
	        "Rb", "RB",
	        "Cs", "CS",
	        "Mg", "MG",
            "Tl", "TL",
            "Cu", "CU",
            "Ag", "AG",
            "Be", "BE",
            "Ni", "NI",
            "Pt", "PT",
            "Zn", "ZN",
            "Co", "CO",
            "Pd", "PD",
            "Cr", "CR",
            "Fe", "FE",
            "V" ,
            "Mn", "MN",
            "Hg", "HG",
            "Cd", "CD",
            "Yb", "YB",
            "Ca", "CA",
            "Sn", "SN",
            "Pb", "PB",
            "Eu", "EU",
            "Sr", "SR",
            "Sm", "SM",
            "Ba", "BA",
            "Ra", "RA",
            "Al", "AL",
            "In", "IN",
            "Y" ,
            "La", "LA",
            "Ce", "CE",
            "Pr", "PR",
            "Nd", "ND",
            "Gd", "GD",
            "Tb", "TB",
            "Dy", "DY",
            "Er", "ER",
            "Tm", "TM",
            "Lu", "LU",
            "Hf", "HF",
            "Zr", "ZR",
            "U" ,
            "Pu", "PU",
            "Th", "TH"  ]

# a map all metal (resi_name:atom_name)
Metal_map ={"LI" : "Li",
	        "NA" : "Na",
            "K"  : "K" ,
	        "RB" : "Rb",
	        "CS" : "Cs",
	        "MG" : "Mg",
            "TL" : "Tl",
            "CU" : "Cu",
            "AG" : "Ag",
            "BE" : "Be",
            "NI" : "Ni",
            "PT" : "Pt",
            "ZN" : "Zn",
            "CO" : "Co",
            "PD" : "Pd",
            "CR" : "Cr",
            "FE" : "Fe",
            "V"  : "V" ,
            "MN" : "Mn",
            "HG" : "Hg",
            "CD" : "Cd",
            "YB" : "Yb",
            "CA" : "Ca",
            "SN" : "Sn",
            "PB" : "Pb",
            "EU" : "Eu",
            "SR" : "Sr",
            "SM" : "Sm",
            "BA" : "Ba",
            "RA" : "Ra",
            "AL" : "Al",
            "IN" : "In",
            "Y"  : "Y" ,
            "LA" : "La",
            "CE" : "Ce",
            "PR" : "Pr",
            "ND" : "Nd",
            "GD" : "Gd",
            "TB" : "Tb",
            "DY" : "Dy",
            "ER" : "Er",
            "TM" : "Tm",
            "LU" : "Lu",
            "HF" : "Hf",
            "ZR" : "Zr",
            "U"  : "U" ,
            "PU" : "Pu",
            "TH" : "Th" }

# Potential coordination center: add upon discover. (resi_name:atom_name)
MetalCenter_map = { "MG" : "Mg",
                    "TL" : "Tl",
                    "CU" : "Cu",
                    "AG" : "Ag",
                    "BE" : "Be",
                    "NI" : "Ni",
                    "PT" : "Pt",
                    "ZN" : "Zn",
                    "CO" : "Co",
                    "PD" : "Pd",
                    "CR" : "Cr",
                    "FE" : "Fe",
                    "V"  : "V" ,
                    "MN" : "Mn",
                    "HG" : "Hg",
                    "CD" : "Cd",
                    "YB" : "Yb",
                    "CA" : "Ca",
                    "SN" : "Sn",
                    "PB" : "Pb",
                    "EU" : "Eu",
                    "SR" : "Sr",
                    "SM" : "Sm",
                    "BA" : "Ba",
                    "RA" : "Ra",
                    "AL" : "Al",
                    "IN" : "In",
                    "Y"  : "Y" ,
                    "LA" : "La",
                    "CE" : "Ce",
                    "PR" : "Pr",
                    "ND" : "Nd",
                    "GD" : "Gd",
                    "TB" : "Tb",
                    "DY" : "Dy",
                    "ER" : "Er",
                    "TM" : "Tm",
                    "LU" : "Lu",
                    "HF" : "Hf",
                    "ZR" : "Zr",
                    "U"  : "U" ,
                    "PU" : "Pu",
                    "TH" : "Th" }

# A map for element conversio, independent of the grammer.
# Amber: base on a Amber18 LEaP ff14SB output
Resi_Ele_map = {'Amber': {    'C' : 'C',
                              'CA' : 'C',
                              'CB' : 'C',
                              'CD' : 'C',
                              'CD1' : 'C',
                              'CD2' : 'C',
                              'CE' : 'C',
                              'CE1' : 'C',
                              'CE2' : 'C',
                              'CE3' : 'C',
                              'CG' : 'C',
                              'CG1' : 'C',
                              'CG2' : 'C',
                              'CH2' : 'C',
                              'CZ' : 'C',
                              'CZ2' : 'C',
                              'CZ3' : 'C',
                              'H' : 'H',
                              'H1' : 'H',
                              'H2' : 'H',
                              'H3' : 'H',
                              'HA' : 'H',
                              'HA2' : 'H',
                              'HA3' : 'H',
                              'HB' : 'H',
                              'HB1' : 'H',
                              'HB2' : 'H',
                              'HB3' : 'H',
                              'HD1' : 'H',
                              'HD11' : 'H',
                              'HD12' : 'H',
                              'HD13' : 'H',
                              'HD2' : 'H',
                              'HD21' : 'H',
                              'HD22' : 'H',
                              'HD23' : 'H',
                              'HD3' : 'H',
                              'HE' : 'H',
                              'HE1' : 'H',
                              'HE2' : 'H',
                              'HE21' : 'H',
                              'HE22' : 'H',
                              'HE3' : 'H',
                              'HG' : 'H',
                              'HG1' : 'H',
                              'HG11' : 'H',
                              'HG12' : 'H',
                              'HG13' : 'H',
                              'HG2' : 'H',
                              'HG21' : 'H',
                              'HG22' : 'H',
                              'HG23' : 'H',
                              'HG3' : 'H',
                              'HH' : 'H',
                              'HH11' : 'H',
                              'HH12' : 'H',
                              'HH2' : 'H',
                              'HH21' : 'H',
                              'HH22' : 'H',
                              'HZ' : 'H',
                              'HZ1' : 'H',
                              'HZ2' : 'H',
                              'HZ3' : 'H',
                              'N' : 'N',
                              'ND1' : 'N',
                              'ND2' : 'N',
                              'NE' : 'N',
                              'NE1' : 'N',
                              'NE2' : 'N',
                              'NH1' : 'N',
                              'NH2' : 'N',
                              'NZ' : 'N',
                              'O' : 'O',
                              'OD1' : 'O',
                              'OD2' : 'O',
                              'OE1' : 'O',
                              'OE2' : 'O',
                              'OG' : 'O',
                              'OG1' : 'O',
                              'OH' : 'O',
                              'OXT' : 'O',
                              'SD' : 'S',
                              'SG' : 'S',
                              "LI" : "Li",
                              "NA" : "Na",
                              "K"  : "K" ,
                              "RB" : "Rb",
                              "CS" : "Cs",
                              "MG" : "Mg",
                              "TL" : "Tl",
                              "CU" : "Cu",
                              "AG" : "Ag",
                              "BE" : "Be",
                              "NI" : "Ni",
                              "PT" : "Pt",
                              "ZN" : "Zn",
                              "CO" : "Co",
                              "PD" : "Pd",
                              "CR" : "Cr",
                              "FE" : "Fe",
                              "V"  : "V" ,
                              "MN" : "Mn",
                              "HG" : "Hg",
                              "CD" : "Cd",
                              "YB" : "Yb",
                              "CA" : "Ca",
                              "SN" : "Sn",
                              "PB" : "Pb",
                              "EU" : "Eu",
                              "SR" : "Sr",
                              "SM" : "Sm",
                              "BA" : "Ba",
                              "RA" : "Ra",
                              "AL" : "Al",
                              "IN" : "In",
                              "Y"  : "Y" ,
                              "LA" : "La",
                              "CE" : "Ce",
                              "PR" : "Pr",
                              "ND" : "Nd",
                              "GD" : "Gd",
                              "TB" : "Tb",
                              "DY" : "Dy",
                              "ER" : "Er",
                              "TM" : "Tm",
                              "LU" : "Lu",
                              "HF" : "Hf",
                              "ZR" : "Zr",
                              "U"  : "U" ,
                              "PU" : "Pu",
                              "TH" : "Th" }       }

# Potential coordination donor: add upon discover. (atom name - base on the atom type definition in the force field)
# ========= Side chain Heteroatoms (O,N,S) ==============
# Amber: base on a Amber18 LEaP ff14SB output

Donor_atom_list={'Amber': [   'NH2', 'NE', 'NH1',
                              'ND1', 'NE2',
                              'NZ',
                              'OD1', 'OD2',
                              'OE1', 'OE2',
                              'OG',
                              'OG1',
                              'ND2', 'OD1',
                              'OE1', 'NE2',
                              'SG',
                              'SD',
                              'OH',
                              'NE1'             ] } 


# A list for residues with ambiguous protonation state that have potential deprotonation
AmbProton_list = [  'ASH','ASP',
                    'CYS','CYM',
                    'GLH','GLU',
              'HIP','HIE',
                    'HID',
              'LYS','LYN',
                    'TYR','TYM',
              'ARG','AR0']

# a map of residue name of deprotonation {resi_name : (depro_resi_name, depro_proton_name), ...}
# atom name base on a Amber18 LEaP ff14SB output   
DeProton_map = {    'ASH' : ('ASP','HD2'),
                    'CYS' : ('CYM','HG' ),
                    'GLH' : ('GLU','HE2'),
              'HIP' : (('HIE', 'HD1'), ('HID', 'HE2')),
              'HID' : None,   # depending on the T_atom, no default method
              'HIE' : None,
              'LYS' : ('LYN','HZ1'),
                    'TYR' : ('TYM','HH'),
              'ARG' : ('AR0','HH22')}

NoProton_list = ['ASP', 'GLU', 'MET'] 

# reference: doi:10.1107/S0567739476001551 (element : radius)
Ionic_radius_map= { "N"  : 1.32, 
                    "O"  : 1.26, 
                    "S"  : 1.70, 
                    "Mg" : 0.86, 
                    "Li" : 0.90, 
                    "Tl" : None, 
                    "Cu" : None, 
                    "Ag" : None, 
                    "Be" : None, 
                    "Ni" : None, 
                    "Pt" : None, 
                    "Zn" : 0.88, 
                    "Co" : None, 
                    "Pd" : None, 
                    "Cr" : None, 
                    "Fe" : None, 
                    "V"  : None, 
                    "Mn" : None, 
                    "Hg" : None, 
                    "Cd" : None, 
                    "Yb" : None, 
                    "Ca" : 1.14, 
                    "Sn" : None, 
                    "Pb" : None, 
                    "Eu" : None, 
                    "Sr" : None, 
                    "Sm" : None, 
                    "Ba" : None, 
                    "Ra" : None, 
                    "Al" : None, 
                    "In" : None, 
                    "Y"  : None, 
                    "La" : None, 
                    "Ce" : None, 
                    "Pr" : None, 
                    "Nd" : None, 
                    "Gd" : None, 
                    "Tb" : None, 
                    "Dy" : None, 
                    "Er" : None, 
                    "Tm" : None, 
                    "Lu" : None, 
                    "Hf" : None, 
                    "Zr" : None, 
                    "U"  : None, 
                    "Pu" : None, 
                    "Th" : None }

# reference:  doi:10.1021/jp8111556 (element : radius)
VDW_radius_map = {  "N"  : 1.55, 
                    "O"  : 1.52, 
                    "S"  : 1.80, 
                    "Mg" : 1.73, 
                    "Li" : 1.82,
                    "Tl" : 1.96, 
                    "Cu" : 1.40, 
                    "Ag" : 1.72, 
                    "Be" : 1.53, 
                    "Ni" : 1.63, 
                    "Pt" : 1.75, 
                    "Zn" : 1.39, 
                    "Co" : None, 
                    "Pd" : 1.63, 
                    "Cr" : None, 
                    "Fe" : None, 
                    "V"  : None, 
                    "Mn" : None, 
                    "Hg" : 1.55, 
                    "Cd" : 1.58, 
                    "Yb" : None, 
                    "Ca" : 2.31, 
                    "Sn" : 2.17, 
                    "Pb" : 2.02, 
                    "Eu" : None, 
                    "Sr" : 2.49, 
                    "Sm" : None, 
                    "Ba" : 2.68, 
                    "Ra" : 2.83, 
                    "Al" : 1.84, 
                    "In" : 1.93, 
                    "Y"  : None, 
                    "La" : None, 
                    "Ce" : None, 
                    "Pr" : None, 
                    "Nd" : None, 
                    "Gd" : None, 
                    "Tb" : None, 
                    "Dy" : None, 
                    "Er" : None, 
                    "Tm" : None, 
                    "Lu" : None, 
                    "Hf" : None, 
                    "Zr" : None, 
                    "U"  : None, 
                    "Pu" : None, 
                    "Th" : None }

# from amino12.lib about residue and connectivity

resi_atom_list = {'ALA' : ['N', 'H', 'CA', 'HA', 'CB', 'HB1', 'HB2', 'HB3', 'C', 'O'],
                  'ARG' : ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'HG2', 'HG3', 'CD', 'HD2', 'HD3', 'NE', 'HE', 'CZ', 'NH1', 'HH11', 'HH12', 'NH2', 'HH21', 'HH22', 'C', 'O'],
                  'ASH' : ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'OD1', 'OD2', 'HD2', 'C', 'O'],
                  'ASN' : ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'OD1', 'ND2', 'HD21', 'HD22', 'C', 'O'],
                  'ASP' : ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'OD1', 'OD2', 'C', 'O'],
                  'CYM' : ['N', 'H', 'CA', 'HA', 'CB', 'HB3', 'HB2', 'SG', 'C', 'O'],
                  'CYS' : ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'SG', 'HG', 'C', 'O'],
                  'CYX' : ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'SG', 'C', 'O'],
                  'GLH' : ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'HG2', 'HG3', 'CD', 'OE1', 'OE2', 'HE2', 'C', 'O'],
                  'GLN' : ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'HG2', 'HG3', 'CD', 'OE1', 'NE2', 'HE21', 'HE22', 'C', 'O'],
                  'GLU' : ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'HG2', 'HG3', 'CD', 'OE1', 'OE2', 'C', 'O'],
                  'GLY' : ['N', 'H', 'CA', 'HA2', 'HA3', 'C', 'O'],
                  'HID' : ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'ND1', 'HD1', 'CE1', 'HE1', 'NE2', 'CD2', 'HD2', 'C', 'O'],
                  'HIE' : ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'ND1', 'CE1', 'HE1', 'NE2', 'HE2', 'CD2', 'HD2', 'C', 'O'],
                  'HIP' : ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'ND1', 'HD1', 'CE1', 'HE1', 'NE2', 'HE2', 'CD2', 'HD2', 'C', 'O'],
                  'HYP' : ['N', 'CD', 'HD22', 'HD23', 'CG', 'HG', 'OD1', 'HD1', 'CB', 'HB2', 'HB3', 'CA', 'HA', 'C', 'O'],
                  'ILE' : ['N', 'H', 'CA', 'HA', 'CB', 'HB', 'CG2', 'HG21', 'HG22', 'HG23', 'CG1', 'HG12', 'HG13', 'CD1', 'HD11', 'HD12', 'HD13', 'C', 'O'],
                  'LEU' : ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'HG', 'CD1', 'HD11', 'HD12', 'HD13', 'CD2', 'HD21', 'HD22', 'HD23', 'C', 'O'],
                  'LYN' : ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'HG2', 'HG3', 'CD', 'HD2', 'HD3', 'CE', 'HE2', 'HE3', 'NZ', 'HZ2', 'HZ3', 'C', 'O'],
                  'LYS' : ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'HG2', 'HG3', 'CD', 'HD2', 'HD3', 'CE', 'HE2', 'HE3', 'NZ', 'HZ1', 'HZ2', 'HZ3', 'C', 'O'],
                  'MET' : ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'HG2', 'HG3', 'SD', 'CE', 'HE1', 'HE2', 'HE3', 'C', 'O'],
                  'PHE' : ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'CD1', 'HD1', 'CE1', 'HE1', 'CZ', 'HZ', 'CE2', 'HE2', 'CD2', 'HD2', 'C', 'O'],
                  'PRO' : ['N', 'CD', 'HD2', 'HD3', 'CG', 'HG2', 'HG3', 'CB', 'HB2', 'HB3', 'CA', 'HA', 'C', 'O'],
                  'SER' : ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'OG', 'HG', 'C', 'O'],
                  'THR' : ['N', 'H', 'CA', 'HA', 'CB', 'HB', 'CG2', 'HG21', 'HG22', 'HG23', 'OG1', 'HG1', 'C', 'O'],
                  'TRP' : ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'CD1', 'HD1', 'NE1', 'HE1', 'CE2', 'CZ2', 'HZ2', 'CH2', 'HH2', 'CZ3', 'HZ3', 'CE3', 'HE3', 'CD2', 'C', 'O'],
                  'TYR' : ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'CD1', 'HD1', 'CE1', 'HE1', 'CZ', 'OH', 'HH', 'CE2', 'HE2', 'CD2', 'HD2', 'C', 'O'],
                  'VAL' : ['N', 'H', 'CA', 'HA', 'CB', 'HB', 'CG1', 'HG11', 'HG12', 'HG13', 'CG2', 'HG21', 'HG22', 'HG23', 'C', 'O'] }

resi_cnt_map = {  'ALA': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB1', 'HB2', 'HB3'], 'HB1': ['CB'], 'HB2': ['CB'], 'HB3': ['CB'], 'C': ['CA', 'O'], 'O': ['C']},
                  'ARG': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'HG2', 'HG3', 'CD'], 'HG2': ['CG'], 'HG3': ['CG'], 'CD': ['CG', 'HD2', 'HD3', 'NE'], 'HD2': ['CD'], 'HD3': ['CD'], 'NE': ['CD', 'HE', 'CZ'], 'HE': ['NE'], 'CZ': ['NE', 'NH1', 'NH2'], 'NH1': ['CZ', 'HH11', 'HH12'], 'HH11': ['NH1'], 'HH12': ['NH1'], 'NH2': ['CZ', 'HH21', 'HH22'], 'HH21': ['NH2'], 'HH22': ['NH2'], 'C': ['CA', 'O'], 'O': ['C']},
                  'ASH': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'OD1', 'OD2'], 'OD1': ['CG'], 'OD2': ['CG', 'HD2'], 'HD2': ['OD2'], 'C': ['CA', 'O'], 'O': ['C']},
                  'ASN': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'OD1', 'ND2'], 'OD1': ['CG'], 'ND2': ['CG', 'HD21', 'HD22'], 'HD21': ['ND2'], 'HD22': ['ND2'], 'C': ['CA', 'O'], 'O': ['C']},
                  'ASP': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'OD1', 'OD2'], 'OD1': ['CG'], 'OD2': ['CG'], 'C': ['CA', 'O'], 'O': ['C']},
                  'CYM': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB3', 'HB2', 'SG'], 'HB3': ['CB'], 'HB2': ['CB'], 'SG': ['CB'], 'C': ['CA', 'O'], 'O': ['C']},
                  'CYS': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'SG'], 'HB2': ['CB'], 'HB3': ['CB'], 'SG': ['CB', 'HG'], 'HG': ['SG'], 'C': ['CA', 'O'], 'O': ['C']},
                  'CYX': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'SG'], 'HB2': ['CB'], 'HB3': ['CB'], 'SG': ['CB'], 'C': ['CA', 'O'], 'O': ['C']},
                  'GLH': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'HG2', 'HG3', 'CD'], 'HG2': ['CG'], 'HG3': ['CG'], 'CD': ['CG', 'OE1', 'OE2'], 'OE1': ['CD'], 'OE2': ['CD', 'HE2'], 'HE2': ['OE2'], 'C': ['CA', 'O'], 'O': ['C']},
                  'GLN': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'HG2', 'HG3', 'CD'], 'HG2': ['CG'], 'HG3': ['CG'], 'CD': ['CG', 'OE1', 'NE2'], 'OE1': ['CD'], 'NE2': ['CD', 'HE21', 'HE22'], 'HE21': ['NE2'], 'HE22': ['NE2'], 'C': ['CA', 'O'], 'O': ['C']},
                  'GLU': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'HG2', 'HG3', 'CD'], 'HG2': ['CG'], 'HG3': ['CG'], 'CD': ['CG', 'OE1', 'OE2'], 'OE1': ['CD'], 'OE2': ['CD'], 'C': ['CA', 'O'], 'O': ['C']},
                  'GLY': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA2', 'HA3', 'C'], 'HA2': ['CA'], 'HA3': ['CA'], 'C': ['CA', 'O'], 'O': ['C']},
                  'HID': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'ND1', 'CD2'], 'ND1': ['CG', 'HD1', 'CE1'], 'HD1': ['ND1'], 'CE1': ['ND1', 'HE1', 'NE2'], 'HE1': ['CE1'], 'NE2': ['CE1', 'CD2'], 'CD2': ['CG', 'NE2', 'HD2'], 'HD2': ['CD2'], 'C': ['CA', 'O'], 'O': ['C']},
                  'HIE': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'ND1', 'CD2'], 'ND1': ['CG', 'CE1'], 'CE1': ['ND1', 'HE1', 'NE2'], 'HE1': ['CE1'], 'NE2': ['CE1', 'HE2', 'CD2'], 'HE2': ['NE2'], 'CD2': ['CG', 'NE2', 'HD2'], 'HD2': ['CD2'], 'C': ['CA', 'O'], 'O': ['C']},
                  'HIP': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'ND1', 'CD2'], 'ND1': ['CG', 'HD1', 'CE1'], 'HD1': ['ND1'], 'CE1': ['ND1', 'HE1', 'NE2'], 'HE1': ['CE1'], 'NE2': ['CE1', 'HE2', 'CD2'], 'HE2': ['NE2'], 'CD2': ['CG', 'NE2', 'HD2'], 'HD2': ['CD2'], 'C': ['CA', 'O'], 'O': ['C']},
                  'HYP': {'N': ['CD', 'CA'], 'CD': ['N', 'HD22', 'HD23', 'CG'], 'HD22': ['CD'], 'HD23': ['CD'], 'CG': ['CD', 'HG', 'OD1', 'CB'], 'HG': ['CG'], 'OD1': ['CG', 'HD1'], 'HD1': ['OD1'], 'CB': ['CG', 'HB2', 'HB3', 'CA'], 'HB2': ['CB'], 'HB3': ['CB'], 'CA': ['N', 'CB', 'HA', 'C'], 'HA': ['CA'], 'C': ['CA', 'O'], 'O': ['C']},
                  'ILE': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB', 'CG2', 'CG1'], 'HB': ['CB'], 'CG2': ['CB', 'HG21', 'HG22', 'HG23'], 'HG21': ['CG2'], 'HG22': ['CG2'], 'HG23': ['CG2'], 'CG1': ['CB', 'HG12', 'HG13', 'CD1'], 'HG12': ['CG1'], 'HG13': ['CG1'], 'CD1': ['CG1', 'HD11', 'HD12', 'HD13'], 'HD11': ['CD1'], 'HD12': ['CD1'], 'HD13': ['CD1'], 'C': ['CA', 'O'], 'O': ['C']},
                  'LEU': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'HG', 'CD1', 'CD2'], 'HG': ['CG'], 'CD1': ['CG', 'HD11', 'HD12', 'HD13'], 'HD11': ['CD1'], 'HD12': ['CD1'], 'HD13': ['CD1'], 'CD2': ['CG', 'HD21', 'HD22', 'HD23'], 'HD21': ['CD2'], 'HD22': ['CD2'], 'HD23': ['CD2'], 'C': ['CA', 'O'], 'O': ['C']},
                  'LYN': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'HG2', 'HG3', 'CD'], 'HG2': ['CG'], 'HG3': ['CG'], 'CD': ['CG', 'HD2', 'HD3', 'CE'], 'HD2': ['CD'], 'HD3': ['CD'], 'CE': ['CD', 'HE2', 'HE3', 'NZ'], 'HE2': ['CE'], 'HE3': ['CE'], 'NZ': ['CE', 'HZ2', 'HZ3'], 'HZ2': ['NZ'], 'HZ3': ['NZ'], 'C': ['CA', 'O'], 'O': ['C']},
                  'LYS': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'HG2', 'HG3', 'CD'], 'HG2': ['CG'], 'HG3': ['CG'], 'CD': ['CG', 'HD2', 'HD3', 'CE'], 'HD2': ['CD'], 'HD3': ['CD'], 'CE': ['CD', 'HE2', 'HE3', 'NZ'], 'HE2': ['CE'], 'HE3': ['CE'], 'NZ': ['CE', 'HZ1', 'HZ2', 'HZ3'], 'HZ1': ['NZ'], 'HZ2': ['NZ'], 'HZ3': ['NZ'], 'C': ['CA', 'O'], 'O': ['C']},
                  'MET': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'HG2', 'HG3', 'SD'], 'HG2': ['CG'], 'HG3': ['CG'], 'SD': ['CG', 'CE'], 'CE': ['SD', 'HE1', 'HE2', 'HE3'], 'HE1': ['CE'], 'HE2': ['CE'], 'HE3': ['CE'], 'C': ['CA', 'O'], 'O': ['C']},
                  'PHE': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'CD1', 'CD2'], 'CD1': ['CG', 'HD1', 'CE1'], 'HD1': ['CD1'], 'CE1': ['CD1', 'HE1', 'CZ'], 'HE1': ['CE1'], 'CZ': ['CE1', 'HZ', 'CE2'], 'HZ': ['CZ'], 'CE2': ['CZ', 'HE2', 'CD2'], 'HE2': ['CE2'], 'CD2': ['CG', 'CE2', 'HD2'], 'HD2': ['CD2'], 'C': ['CA', 'O'], 'O': ['C']},
                  'PRO': {'N': ['CD', 'CA'], 'CD': ['N', 'HD2', 'HD3', 'CG'], 'HD2': ['CD'], 'HD3': ['CD'], 'CG': ['CD', 'HG2', 'HG3', 'CB'], 'HG2': ['CG'], 'HG3': ['CG'], 'CB': ['CG', 'HB2', 'HB3', 'CA'], 'HB2': ['CB'], 'HB3': ['CB'], 'CA': ['N', 'CB', 'HA', 'C'], 'HA': ['CA'], 'C': ['CA', 'O'], 'O': ['C']},
                  'SER': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'OG'], 'HB2': ['CB'], 'HB3': ['CB'], 'OG': ['CB', 'HG'], 'HG': ['OG'], 'C': ['CA', 'O'], 'O': ['C']},
                  'THR': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB', 'CG2', 'OG1'], 'HB': ['CB'], 'CG2': ['CB', 'HG21', 'HG22', 'HG23'], 'HG21': ['CG2'], 'HG22': ['CG2'], 'HG23': ['CG2'], 'OG1': ['CB', 'HG1'], 'HG1': ['OG1'], 'C': ['CA', 'O'], 'O': ['C']},
                  'TRP': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'CD1', 'CD2'], 'CD1': ['CG', 'HD1', 'NE1'], 'HD1': ['CD1'], 'NE1': ['CD1', 'HE1', 'CE2'], 'HE1': ['NE1'], 'CE2': ['NE1', 'CZ2', 'CD2'], 'CZ2': ['CE2', 'HZ2', 'CH2'], 'HZ2': ['CZ2'], 'CH2': ['CZ2', 'HH2', 'CZ3'], 'HH2': ['CH2'], 'CZ3': ['CH2', 'HZ3', 'CE3'], 'HZ3': ['CZ3'], 'CE3': ['CZ3', 'HE3', 'CD2'], 'HE3': ['CE3'], 'CD2': ['CG', 'CE2', 'CE3'], 'C': ['CA', 'O'], 'O': ['C']},
                  'TYR': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'CD1', 'CD2'], 'CD1': ['CG', 'HD1', 'CE1'], 'HD1': ['CD1'], 'CE1': ['CD1', 'HE1', 'CZ'], 'HE1': ['CE1'], 'CZ': ['CE1', 'OH', 'CE2'], 'OH': ['CZ', 'HH'], 'HH': ['OH'], 'CE2': ['CZ', 'HE2', 'CD2'], 'HE2': ['CE2'], 'CD2': ['CG', 'CE2', 'HD2'], 'HD2': ['CD2'], 'C': ['CA', 'O'], 'O': ['C']},
                  'VAL': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB', 'CG1', 'CG2'], 'HB': ['CB'], 'CG1': ['CB', 'HG11', 'HG12', 'HG13'], 'HG11': ['CG1'], 'HG12': ['CG1'], 'HG13': ['CG1'], 'CG2': ['CB', 'HG21', 'HG22', 'HG23'], 'HG21': ['CG2'], 'HG22': ['CG2'], 'HG23': ['CG2'], 'C': ['CA', 'O'], 'O': ['C']} }

# C terminal
resi_ct_atom_list = {   'ALA': ['N', 'H', 'CA', 'HA', 'CB', 'HB1', 'HB2', 'HB3', 'C', 'O', 'OXT'],
                        'ARG': ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'HG2', 'HG3', 'CD', 'HD2', 'HD3', 'NE', 'HE', 'CZ', 'NH1', 'HH11', 'HH12', 'NH2', 'HH21', 'HH22', 'C', 'O', 'OXT'],
                        'ASN': ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'OD1', 'ND2', 'HD21', 'HD22', 'C', 'O', 'OXT'],
                        'ASP': ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'OD1', 'OD2', 'C', 'O', 'OXT'],
                        'CYS': ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'SG', 'HG', 'C', 'O', 'OXT'],
                        'CYX': ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'SG', 'C', 'O', 'OXT'],
                        'GLN': ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'HG2', 'HG3', 'CD', 'OE1', 'NE2', 'HE21', 'HE22', 'C', 'O', 'OXT'],
                        'GLU': ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'HG2', 'HG3', 'CD', 'OE1', 'OE2', 'C', 'O', 'OXT'],
                        'GLY': ['N', 'H', 'CA', 'HA2', 'HA3', 'C', 'O', 'OXT'],
                        'HID': ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'ND1', 'HD1', 'CE1', 'HE1', 'NE2', 'CD2', 'HD2', 'C', 'O', 'OXT'],
                        'HIE': ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'ND1', 'CE1', 'HE1', 'NE2', 'HE2', 'CD2', 'HD2', 'C', 'O', 'OXT'],
                        'HIP': ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'ND1', 'HD1', 'CE1', 'HE1', 'NE2', 'HE2', 'CD2', 'HD2', 'C', 'O', 'OXT'],
                        'HYP': ['N', 'CD', 'HD22', 'HD23', 'CG', 'HG', 'OD1', 'HD1', 'CB', 'HB2', 'HB3', 'CA', 'HA', 'C', 'O', 'OXT'],
                        'ILE': ['N', 'H', 'CA', 'HA', 'CB', 'HB', 'CG2', 'HG21', 'HG22', 'HG23', 'CG1', 'HG12', 'HG13', 'CD1', 'HD11', 'HD12', 'HD13', 'C', 'O', 'OXT'],
                        'LEU': ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'HG', 'CD1', 'HD11', 'HD12', 'HD13', 'CD2', 'HD21', 'HD22', 'HD23', 'C', 'O', 'OXT'],
                        'LYS': ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'HG2', 'HG3', 'CD', 'HD2', 'HD3', 'CE', 'HE2', 'HE3', 'NZ', 'HZ1', 'HZ2', 'HZ3', 'C', 'O', 'OXT'],
                        'MET': ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'HG2', 'HG3', 'SD', 'CE', 'HE1', 'HE2', 'HE3', 'C', 'O', 'OXT'],
                        'PHE': ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'CD1', 'HD1', 'CE1', 'HE1', 'CZ', 'HZ', 'CE2', 'HE2', 'CD2', 'HD2', 'C', 'O', 'OXT'],
                        'PRO': ['N', 'CD', 'HD2', 'HD3', 'CG', 'HG2', 'HG3', 'CB', 'HB2', 'HB3', 'CA', 'HA', 'C', 'O', 'OXT'],
                        'SER': ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'OG', 'HG', 'C', 'O', 'OXT'],
                        'THR': ['N', 'H', 'CA', 'HA', 'CB', 'HB', 'CG2', 'HG21', 'HG22', 'HG23', 'OG1', 'HG1', 'C', 'O', 'OXT'],
                        'TRP': ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'CD1', 'HD1', 'NE1', 'HE1', 'CE2', 'CZ2', 'HZ2', 'CH2', 'HH2', 'CZ3', 'HZ3', 'CE3', 'HE3', 'CD2', 'C', 'O', 'OXT'],
                        'TYR': ['N', 'H', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'CD1', 'HD1', 'CE1', 'HE1', 'CZ', 'OH', 'HH', 'CE2', 'HE2', 'CD2', 'HD2', 'C', 'O', 'OXT'],
                        'VAL': ['N', 'H', 'CA', 'HA', 'CB', 'HB', 'CG1', 'HG11', 'HG12', 'HG13', 'CG2', 'HG21', 'HG22', 'HG23', 'C', 'O', 'OXT'],
                        'NHE': ['N', 'HN1', 'HN2'],
                        'NME': ['N', 'H', 'CH3', 'HH31', 'HH32', 'HH33'] }

resi_ct_cnt_map = {     'ALA': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB1', 'HB2', 'HB3'], 'HB1': ['CB'], 'HB2': ['CB'], 'HB3': ['CB'], 'C': ['CA', 'O', 'OXT'], 'O': ['C'], 'OXT': ['C']},
                        'ARG': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'HG2', 'HG3', 'CD'], 'HG2': ['CG'], 'HG3': ['CG'], 'CD': ['CG', 'HD2', 'HD3', 'NE'], 'HD2': ['CD'], 'HD3': ['CD'], 'NE': ['CD', 'HE', 'CZ'], 'HE': ['NE'], 'CZ': ['NE', 'NH1', 'NH2'], 'NH1': ['CZ', 'HH11', 'HH12'], 'HH11': ['NH1'], 'HH12': ['NH1'], 'NH2': ['CZ', 'HH21', 'HH22'], 'HH21': ['NH2'], 'HH22': ['NH2'], 'C': ['CA', 'O', 'OXT'], 'O': ['C'], 'OXT': ['C']},
                        'ASN': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'OD1', 'ND2'], 'OD1': ['CG'], 'ND2': ['CG', 'HD21', 'HD22'], 'HD21': ['ND2'], 'HD22': ['ND2'], 'C': ['CA', 'O', 'OXT'], 'O': ['C'], 'OXT': ['C']},
                        'ASP': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'OD1', 'OD2'], 'OD1': ['CG'], 'OD2': ['CG'], 'C': ['CA', 'O', 'OXT'], 'O': ['C'], 'OXT': ['C']},
                        'CYS': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'SG'], 'HB2': ['CB'], 'HB3': ['CB'], 'SG': ['CB', 'HG'], 'HG': ['SG'], 'C': ['CA', 'O', 'OXT'], 'O': ['C'], 'OXT': ['C']},
                        'CYX': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'SG'], 'HB2': ['CB'], 'HB3': ['CB'], 'SG': ['CB'], 'C': ['CA', 'O', 'OXT'], 'O': ['C'], 'OXT': ['C']},
                        'GLN': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'HG2', 'HG3', 'CD'], 'HG2': ['CG'], 'HG3': ['CG'], 'CD': ['CG', 'OE1', 'NE2'], 'OE1': ['CD'], 'NE2': ['CD', 'HE21', 'HE22'], 'HE21': ['NE2'], 'HE22': ['NE2'], 'C': ['CA', 'O', 'OXT'], 'O': ['C'], 'OXT': ['C']},
                        'GLU': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'HG2', 'HG3', 'CD'], 'HG2': ['CG'], 'HG3': ['CG'], 'CD': ['CG', 'OE1', 'OE2'], 'OE1': ['CD'], 'OE2': ['CD'], 'C': ['CA', 'O', 'OXT'], 'O': ['C'], 'OXT': ['C']},
                        'GLY': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA2', 'HA3', 'C'], 'HA2': ['CA'], 'HA3': ['CA'], 'C': ['CA', 'O', 'OXT'], 'O': ['C'], 'OXT': ['C']},
                        'HID': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'ND1', 'CD2'], 'ND1': ['CG', 'HD1', 'CE1'], 'HD1': ['ND1'], 'CE1': ['ND1', 'HE1', 'NE2'], 'HE1': ['CE1'], 'NE2': ['CE1', 'CD2'], 'CD2': ['CG', 'NE2', 'HD2'], 'HD2': ['CD2'], 'C': ['CA', 'O', 'OXT'], 'O': ['C'], 'OXT': ['C']},
                        'HIE': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'ND1', 'CD2'], 'ND1': ['CG', 'CE1'], 'CE1': ['ND1', 'HE1', 'NE2'], 'HE1': ['CE1'], 'NE2': ['CE1', 'HE2', 'CD2'], 'HE2': ['NE2'], 'CD2': ['CG', 'NE2', 'HD2'], 'HD2': ['CD2'], 'C': ['CA', 'O', 'OXT'], 'O': ['C'], 'OXT': ['C']},
                        'HIP': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'ND1', 'CD2'], 'ND1': ['CG', 'HD1', 'CE1'], 'HD1': ['ND1'], 'CE1': ['ND1', 'HE1', 'NE2'], 'HE1': ['CE1'], 'NE2': ['CE1', 'HE2', 'CD2'], 'HE2': ['NE2'], 'CD2': ['CG', 'NE2', 'HD2'], 'HD2': ['CD2'], 'C': ['CA', 'O', 'OXT'], 'O': ['C'], 'OXT': ['C']},
                        'HYP': {'N': ['CD', 'CA'], 'CD': ['N', 'HD22', 'HD23', 'CG'], 'HD22': ['CD'], 'HD23': ['CD'], 'CG': ['CD', 'HG', 'OD1', 'CB'], 'HG': ['CG'], 'OD1': ['CG', 'HD1'], 'HD1': ['OD1'], 'CB': ['CG', 'HB2', 'HB3', 'CA'], 'HB2': ['CB'], 'HB3': ['CB'], 'CA': ['N', 'CB', 'HA', 'C'], 'HA': ['CA'], 'C': ['CA', 'O', 'OXT'], 'O': ['C'], 'OXT': ['C']},
                        'ILE': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB', 'CG2', 'CG1'], 'HB': ['CB'], 'CG2': ['CB', 'HG21', 'HG22', 'HG23'], 'HG21': ['CG2'], 'HG22': ['CG2'], 'HG23': ['CG2'], 'CG1': ['CB', 'HG12', 'HG13', 'CD1'], 'HG12': ['CG1'], 'HG13': ['CG1'], 'CD1': ['CG1', 'HD11', 'HD12', 'HD13'], 'HD11': ['CD1'], 'HD12': ['CD1'], 'HD13': ['CD1'], 'C': ['CA', 'O', 'OXT'], 'O': ['C'], 'OXT': ['C']},
                        'LEU': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'HG', 'CD1', 'CD2'], 'HG': ['CG'], 'CD1': ['CG', 'HD11', 'HD12', 'HD13'], 'HD11': ['CD1'], 'HD12': ['CD1'], 'HD13': ['CD1'], 'CD2': ['CG', 'HD21', 'HD22', 'HD23'], 'HD21': ['CD2'], 'HD22': ['CD2'], 'HD23': ['CD2'], 'C': ['CA', 'O', 'OXT'], 'O': ['C'], 'OXT': ['C']},
                        'LYS': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'HG2', 'HG3', 'CD'], 'HG2': ['CG'], 'HG3': ['CG'], 'CD': ['CG', 'HD2', 'HD3', 'CE'], 'HD2': ['CD'], 'HD3': ['CD'], 'CE': ['CD', 'HE2', 'HE3', 'NZ'], 'HE2': ['CE'], 'HE3': ['CE'], 'NZ': ['CE', 'HZ1', 'HZ2', 'HZ3'], 'HZ1': ['NZ'], 'HZ2': ['NZ'], 'HZ3': ['NZ'], 'C': ['CA', 'O', 'OXT'], 'O': ['C'], 'OXT': ['C']},
                        'MET': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'HG2', 'HG3', 'SD'], 'HG2': ['CG'], 'HG3': ['CG'], 'SD': ['CG', 'CE'], 'CE': ['SD', 'HE1', 'HE2', 'HE3'], 'HE1': ['CE'], 'HE2': ['CE'], 'HE3': ['CE'], 'C': ['CA', 'O', 'OXT'], 'O': ['C'], 'OXT': ['C']},
                        'PHE': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'CD1', 'CD2'], 'CD1': ['CG', 'HD1', 'CE1'], 'HD1': ['CD1'], 'CE1': ['CD1', 'HE1', 'CZ'], 'HE1': ['CE1'], 'CZ': ['CE1', 'HZ', 'CE2'], 'HZ': ['CZ'], 'CE2': ['CZ', 'HE2', 'CD2'], 'HE2': ['CE2'], 'CD2': ['CG', 'CE2', 'HD2'], 'HD2': ['CD2'], 'C': ['CA', 'O', 'OXT'], 'O': ['C'], 'OXT': ['C']},
                        'PRO': {'N': ['CD', 'CA'], 'CD': ['N', 'HD2', 'HD3', 'CG'], 'HD2': ['CD'], 'HD3': ['CD'], 'CG': ['CD', 'HG2', 'HG3', 'CB'], 'HG2': ['CG'], 'HG3': ['CG'], 'CB': ['CG', 'HB2', 'HB3', 'CA'], 'HB2': ['CB'], 'HB3': ['CB'], 'CA': ['N', 'CB', 'HA', 'C'], 'HA': ['CA'], 'C': ['CA', 'O', 'OXT'], 'O': ['C'], 'OXT': ['C']},
                        'SER': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'OG'], 'HB2': ['CB'], 'HB3': ['CB'], 'OG': ['CB', 'HG'], 'HG': ['OG'], 'C': ['CA', 'O', 'OXT'], 'O': ['C'], 'OXT': ['C']},
                        'THR': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB', 'CG2', 'OG1'], 'HB': ['CB'], 'CG2': ['CB', 'HG21', 'HG22', 'HG23'], 'HG21': ['CG2'], 'HG22': ['CG2'], 'HG23': ['CG2'], 'OG1': ['CB', 'HG1'], 'HG1': ['OG1'], 'C': ['CA', 'O', 'OXT'], 'O': ['C'], 'OXT': ['C']},
                        'TRP': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'CD1', 'CD2'], 'CD1': ['CG', 'HD1', 'NE1'], 'HD1': ['CD1'], 'NE1': ['CD1', 'HE1', 'CE2'], 'HE1': ['NE1'], 'CE2': ['NE1', 'CZ2', 'CD2'], 'CZ2': ['CE2', 'HZ2', 'CH2'], 'HZ2': ['CZ2'], 'CH2': ['CZ2', 'HH2', 'CZ3'], 'HH2': ['CH2'], 'CZ3': ['CH2', 'HZ3', 'CE3'], 'HZ3': ['CZ3'], 'CE3': ['CZ3', 'HE3', 'CD2'], 'HE3': ['CE3'], 'CD2': ['CG', 'CE2', 'CE3'], 'C': ['CA', 'O', 'OXT'], 'O': ['C'], 'OXT': ['C']},
                        'TYR': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'CD1', 'CD2'], 'CD1': ['CG', 'HD1', 'CE1'], 'HD1': ['CD1'], 'CE1': ['CD1', 'HE1', 'CZ'], 'HE1': ['CE1'], 'CZ': ['CE1', 'OH', 'CE2'], 'OH': ['CZ', 'HH'], 'HH': ['OH'], 'CE2': ['CZ', 'HE2', 'CD2'], 'HE2': ['CE2'], 'CD2': ['CG', 'CE2', 'HD2'], 'HD2': ['CD2'], 'C': ['CA', 'O', 'OXT'], 'O': ['C'], 'OXT': ['C']},
                        'VAL': {'N': ['H', 'CA'], 'H': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB', 'CG1', 'CG2'], 'HB': ['CB'], 'CG1': ['CB', 'HG11', 'HG12', 'HG13'], 'HG11': ['CG1'], 'HG12': ['CG1'], 'HG13': ['CG1'], 'CG2': ['CB', 'HG21', 'HG22', 'HG23'], 'HG21': ['CG2'], 'HG22': ['CG2'], 'HG23': ['CG2'], 'C': ['CA', 'O', 'OXT'], 'O': ['C'], 'OXT': ['C']},
                        'NHE': {'N': ['HN1', 'HN2'], 'HN1': ['N'], 'HN2': ['N']},
                        'NME': {'N': ['H', 'CH3'], 'H': ['N'], 'CH3': ['N', 'HH31', 'HH32', 'HH33'], 'HH31': ['CH3'], 'HH32': ['CH3'], 'HH33': ['CH3']} }
# N terminal
resi_nt_atom_list = {   'ACE': ['H1', 'CH3', 'H2', 'H3', 'C', 'O'],
                        'ALA': ['N', 'H1', 'H2', 'H3', 'CA', 'HA', 'CB', 'HB1', 'HB2', 'HB3', 'C', 'O'],
                        'ARG': ['N', 'H1', 'H2', 'H3', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'HG2', 'HG3', 'CD', 'HD2', 'HD3', 'NE', 'HE', 'CZ', 'NH1', 'HH11', 'HH12', 'NH2', 'HH21', 'HH22', 'C', 'O'],
                        'ASN': ['N', 'H1', 'H2', 'H3', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'OD1', 'ND2', 'HD21', 'HD22', 'C', 'O'],
                        'ASP': ['N', 'H1', 'H2', 'H3', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'OD1', 'OD2', 'C', 'O'],
                        'CYS': ['N', 'H1', 'H2', 'H3', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'SG', 'HG', 'C', 'O'],
                        'CYX': ['N', 'H1', 'H2', 'H3', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'SG', 'C', 'O'],
                        'GLN': ['N', 'H1', 'H2', 'H3', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'HG2', 'HG3', 'CD', 'OE1', 'NE2', 'HE21', 'HE22', 'C', 'O'],
                        'GLU': ['N', 'H1', 'H2', 'H3', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'HG2', 'HG3', 'CD', 'OE1', 'OE2', 'C', 'O'],
                        'GLY': ['N', 'H1', 'H2', 'H3', 'CA', 'HA2', 'HA3', 'C', 'O'],
                        'HID': ['N', 'H1', 'H2', 'H3', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'ND1', 'HD1', 'CE1', 'HE1', 'NE2', 'CD2', 'HD2', 'C', 'O'],
                        'HIE': ['N', 'H1', 'H2', 'H3', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'ND1', 'CE1', 'HE1', 'NE2', 'HE2', 'CD2', 'HD2', 'C', 'O'],
                        'HIP': ['N', 'H1', 'H2', 'H3', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'ND1', 'HD1', 'CE1', 'HE1', 'NE2', 'HE2', 'CD2', 'HD2', 'C', 'O'],
                        'ILE': ['N', 'H1', 'H2', 'H3', 'CA', 'HA', 'CB', 'HB', 'CG2', 'HG21', 'HG22', 'HG23', 'CG1', 'HG12', 'HG13', 'CD1', 'HD11', 'HD12', 'HD13', 'C', 'O'],
                        'LEU': ['N', 'H1', 'H2', 'H3', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'HG', 'CD1', 'HD11', 'HD12', 'HD13', 'CD2', 'HD21', 'HD22', 'HD23', 'C', 'O'],
                        'LYS': ['N', 'H1', 'H2', 'H3', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'HG2', 'HG3', 'CD', 'HD2', 'HD3', 'CE', 'HE2', 'HE3', 'NZ', 'HZ1', 'HZ2', 'HZ3', 'C', 'O'],
                        'MET': ['N', 'H1', 'H2', 'H3', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'HG2', 'HG3', 'SD', 'CE', 'HE1', 'HE2', 'HE3', 'C', 'O'],
                        'PHE': ['N', 'H1', 'H2', 'H3', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'CD1', 'HD1', 'CE1', 'HE1', 'CZ', 'HZ', 'CE2', 'HE2', 'CD2', 'HD2', 'C', 'O'],
                        'PRO': ['N', 'H2', 'H3', 'CD', 'HD2', 'HD3', 'CG', 'HG2', 'HG3', 'CB', 'HB2', 'HB3', 'CA', 'HA', 'C', 'O'],
                        'SER': ['N', 'H1', 'H2', 'H3', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'OG', 'HG', 'C', 'O'],
                        'THR': ['N', 'H1', 'H2', 'H3', 'CA', 'HA', 'CB', 'HB', 'CG2', 'HG21', 'HG22', 'HG23', 'OG1', 'HG1', 'C', 'O'],
                        'TRP': ['N', 'H1', 'H2', 'H3', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'CD1', 'HD1', 'NE1', 'HE1', 'CE2', 'CZ2', 'HZ2', 'CH2', 'HH2', 'CZ3', 'HZ3', 'CE3', 'HE3', 'CD2', 'C', 'O'],
                        'TYR': ['N', 'H1', 'H2', 'H3', 'CA', 'HA', 'CB', 'HB2', 'HB3', 'CG', 'CD1', 'HD1', 'CE1', 'HE1', 'CZ', 'OH', 'HH', 'CE2', 'HE2', 'CD2', 'HD2', 'C', 'O'],
                        'VAL': ['N', 'H1', 'H2', 'H3', 'CA', 'HA', 'CB', 'HB', 'CG1', 'HG11', 'HG12', 'HG13', 'CG2', 'HG21', 'HG22', 'HG23', 'C', 'O'] }

resi_nt_cnt_map = {     'ACE': {'H1': ['CH3'], 'CH3': ['H1', 'H2', 'H3', 'C'], 'H2': ['CH3'], 'H3': ['CH3'], 'C': ['CH3', 'O'], 'O': ['C']},
                        'ALA': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB1', 'HB2', 'HB3'], 'HB1': ['CB'], 'HB2': ['CB'], 'HB3': ['CB'], 'C': ['CA', 'O'], 'O': ['C']},
                        'ARG': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'HG2', 'HG3', 'CD'], 'HG2': ['CG'], 'HG3': ['CG'], 'CD': ['CG', 'HD2', 'HD3', 'NE'], 'HD2': ['CD'], 'HD3': ['CD'], 'NE': ['CD', 'HE', 'CZ'], 'HE': ['NE'], 'CZ': ['NE', 'NH1', 'NH2'], 'NH1': ['CZ', 'HH11', 'HH12'], 'HH11': ['NH1'], 'HH12': ['NH1'], 'NH2': ['CZ', 'HH21', 'HH22'], 'HH21': ['NH2'], 'HH22': ['NH2'], 'C': ['CA', 'O'], 'O': ['C']},
                        'ASN': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'OD1', 'ND2'], 'OD1': ['CG'], 'ND2': ['CG', 'HD21', 'HD22'], 'HD21': ['ND2'], 'HD22': ['ND2'], 'C': ['CA', 'O'], 'O': ['C']},
                        'ASP': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'OD1', 'OD2'], 'OD1': ['CG'], 'OD2': ['CG'], 'C': ['CA', 'O'], 'O': ['C']},
                        'CYS': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'SG'], 'HB2': ['CB'], 'HB3': ['CB'], 'SG': ['CB', 'HG'], 'HG': ['SG'], 'C': ['CA', 'O'], 'O': ['C']},
                        'CYX': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'SG'], 'HB2': ['CB'], 'HB3': ['CB'], 'SG': ['CB'], 'C': ['CA', 'O'], 'O': ['C']},
                        'GLN': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'HG2', 'HG3', 'CD'], 'HG2': ['CG'], 'HG3': ['CG'], 'CD': ['CG', 'OE1', 'NE2'], 'OE1': ['CD'], 'NE2': ['CD', 'HE21', 'HE22'], 'HE21': ['NE2'], 'HE22': ['NE2'], 'C': ['CA', 'O'], 'O': ['C']},
                        'GLU': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'HG2', 'HG3', 'CD'], 'HG2': ['CG'], 'HG3': ['CG'], 'CD': ['CG', 'OE1', 'OE2'], 'OE1': ['CD'], 'OE2': ['CD'], 'C': ['CA', 'O'], 'O': ['C']},
                        'GLY': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA2', 'HA3', 'C'], 'HA2': ['CA'], 'HA3': ['CA'], 'C': ['CA', 'O'], 'O': ['C']},
                        'HID': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'ND1', 'CD2'], 'ND1': ['CG', 'HD1', 'CE1'], 'HD1': ['ND1'], 'CE1': ['ND1', 'HE1', 'NE2'], 'HE1': ['CE1'], 'NE2': ['CE1', 'CD2'], 'CD2': ['CG', 'NE2', 'HD2'], 'HD2': ['CD2'], 'C': ['CA', 'O'], 'O': ['C']},
                        'HIE': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'ND1', 'CD2'], 'ND1': ['CG', 'CE1'], 'CE1': ['ND1', 'HE1', 'NE2'], 'HE1': ['CE1'], 'NE2': ['CE1', 'HE2', 'CD2'], 'HE2': ['NE2'], 'CD2': ['CG', 'NE2', 'HD2'], 'HD2': ['CD2'], 'C': ['CA', 'O'], 'O': ['C']},
                        'HIP': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'ND1', 'CD2'], 'ND1': ['CG', 'HD1', 'CE1'], 'HD1': ['ND1'], 'CE1': ['ND1', 'HE1', 'NE2'], 'HE1': ['CE1'], 'NE2': ['CE1', 'HE2', 'CD2'], 'HE2': ['NE2'], 'CD2': ['CG', 'NE2', 'HD2'], 'HD2': ['CD2'], 'C': ['CA', 'O'], 'O': ['C']},
                        'ILE': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB', 'CG2', 'CG1'], 'HB': ['CB'], 'CG2': ['CB', 'HG21', 'HG22', 'HG23'], 'HG21': ['CG2'], 'HG22': ['CG2'], 'HG23': ['CG2'], 'CG1': ['CB', 'HG12', 'HG13', 'CD1'], 'HG12': ['CG1'], 'HG13': ['CG1'], 'CD1': ['CG1', 'HD11', 'HD12', 'HD13'], 'HD11': ['CD1'], 'HD12': ['CD1'], 'HD13': ['CD1'], 'C': ['CA', 'O'], 'O': ['C']},
                        'LEU': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'HG', 'CD1', 'CD2'], 'HG': ['CG'], 'CD1': ['CG', 'HD11', 'HD12', 'HD13'], 'HD11': ['CD1'], 'HD12': ['CD1'], 'HD13': ['CD1'], 'CD2': ['CG', 'HD21', 'HD22', 'HD23'], 'HD21': ['CD2'], 'HD22': ['CD2'], 'HD23': ['CD2'], 'C': ['CA', 'O'], 'O': ['C']},
                        'LYS': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'HG2', 'HG3', 'CD'], 'HG2': ['CG'], 'HG3': ['CG'], 'CD': ['CG', 'HD2', 'HD3', 'CE'], 'HD2': ['CD'], 'HD3': ['CD'], 'CE': ['CD', 'HE2', 'HE3', 'NZ'], 'HE2': ['CE'], 'HE3': ['CE'], 'NZ': ['CE', 'HZ1', 'HZ2', 'HZ3'], 'HZ1': ['NZ'], 'HZ2': ['NZ'], 'HZ3': ['NZ'], 'C': ['CA', 'O'], 'O': ['C']},
                        'MET': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'HG2', 'HG3', 'SD'], 'HG2': ['CG'], 'HG3': ['CG'], 'SD': ['CG', 'CE'], 'CE': ['SD', 'HE1', 'HE2', 'HE3'], 'HE1': ['CE'], 'HE2': ['CE'], 'HE3': ['CE'], 'C': ['CA', 'O'], 'O': ['C']},
                        'PHE': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'CD1', 'CD2'], 'CD1': ['CG', 'HD1', 'CE1'], 'HD1': ['CD1'], 'CE1': ['CD1', 'HE1', 'CZ'], 'HE1': ['CE1'], 'CZ': ['CE1', 'HZ', 'CE2'], 'HZ': ['CZ'], 'CE2': ['CZ', 'HE2', 'CD2'], 'HE2': ['CE2'], 'CD2': ['CG', 'CE2', 'HD2'], 'HD2': ['CD2'], 'C': ['CA', 'O'], 'O': ['C']},
                        'PRO': {'N': ['H2', 'H3', 'CD', 'CA'], 'H2': ['N'], 'H3': ['N'], 'CD': ['N', 'HD2', 'HD3', 'CG'], 'HD2': ['CD'], 'HD3': ['CD'], 'CG': ['CD', 'HG2', 'HG3', 'CB'], 'HG2': ['CG'], 'HG3': ['CG'], 'CB': ['CG', 'HB2', 'HB3', 'CA'], 'HB2': ['CB'], 'HB3': ['CB'], 'CA': ['N', 'CB', 'HA', 'C'], 'HA': ['CA'], 'C': ['CA', 'O'], 'O': ['C']},
                        'SER': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'OG'], 'HB2': ['CB'], 'HB3': ['CB'], 'OG': ['CB', 'HG'], 'HG': ['OG'], 'C': ['CA', 'O'], 'O': ['C']},
                        'THR': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB', 'CG2', 'OG1'], 'HB': ['CB'], 'CG2': ['CB', 'HG21', 'HG22', 'HG23'], 'HG21': ['CG2'], 'HG22': ['CG2'], 'HG23': ['CG2'], 'OG1': ['CB', 'HG1'], 'HG1': ['OG1'], 'C': ['CA', 'O'], 'O': ['C']},
                        'TRP': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'CD1', 'CD2'], 'CD1': ['CG', 'HD1', 'NE1'], 'HD1': ['CD1'], 'NE1': ['CD1', 'HE1', 'CE2'], 'HE1': ['NE1'], 'CE2': ['NE1', 'CZ2', 'CD2'], 'CZ2': ['CE2', 'HZ2', 'CH2'], 'HZ2': ['CZ2'], 'CH2': ['CZ2', 'HH2', 'CZ3'], 'HH2': ['CH2'], 'CZ3': ['CH2', 'HZ3', 'CE3'], 'HZ3': ['CZ3'], 'CE3': ['CZ3', 'HE3', 'CD2'], 'HE3': ['CE3'], 'CD2': ['CG', 'CE2', 'CE3'], 'C': ['CA', 'O'], 'O': ['C']},
                        'TYR': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'CD1', 'CD2'], 'CD1': ['CG', 'HD1', 'CE1'], 'HD1': ['CD1'], 'CE1': ['CD1', 'HE1', 'CZ'], 'HE1': ['CE1'], 'CZ': ['CE1', 'OH', 'CE2'], 'OH': ['CZ', 'HH'], 'HH': ['OH'], 'CE2': ['CZ', 'HE2', 'CD2'], 'HE2': ['CE2'], 'CD2': ['CG', 'CE2', 'HD2'], 'HD2': ['CD2'], 'C': ['CA', 'O'], 'O': ['C']},
                        'VAL': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB', 'CG1', 'CG2'], 'HB': ['CB'], 'CG1': ['CB', 'HG11', 'HG12', 'HG13'], 'HG11': ['CG1'], 'HG12': ['CG1'], 'HG13': ['CG1'], 'CG2': ['CB', 'HG21', 'HG22', 'HG23'], 'HG21': ['CG2'], 'HG22': ['CG2'], 'HG23': ['CG2'], 'C': ['CA', 'O'], 'O': ['C']} }