__doc__='''
This module include mapping required by the workflow.
------------------------------------------------------------
(MAP) Resi_map
Map residue key with the 3 letter name.
{resi_key:resi_name_3,...}
------------------------------------------------------------
(MAP) Resi_map2
Map 3 letter name with residue key.
{resi_name_3:resi_key,...}
------------------------------------------------------------
(List) Resi_list
Map residue key with index number
[resi_key,...]
------------------------------------------------------------
(???) Atom_topology


------------------------------------------------------------
'''

Resi_map={'R':'ARG',
          'H':'HIS',
          'K':'LYS',
          'D':'ASP',
          'E':'GLU',
          'S':'SER',
          'T':'THR',
          'N':'ASN',
          'Q':'GLN',
          'C':'CYS',
          'U':'SEC',
          'G':'GLY',
          'P':'PRO',
          'A':'ALA',
          'V':'VAL',
          'I':'ILE',
          'L':'LEU',
          'M':'MET',
          'F':'PHE',
          'Y':'TYR',
          'W':'TRP'}

Resi_map2={'ARG':'R',
           'HIS':'H',
           'HIE':'H',
           'HIP':'H',
           'HID':'H',
           'LYS':'K',
           'ASP':'D',
           'GLU':'E',
           'SER':'S',
           'THR':'T',
           'ASN':'N',
           'GLN':'Q',
           'CYS':'C',
           'SEC':'U',
           'GLY':'G',
           'PRO':'P',
           'ALA':'A',
           'VAL':'V',
           'ILE':'I',
           'LEU':'L',
           'MET':'M',
           'PHE':'F',
           'TYR':'Y',
           'TRP':'W'}

Resi_list=['R','H','K','D','E','S','T','N','Q','C','U','G','P','A','V','I','L','M','F','Y','W']

TIP3P_map=[ "O" , "H" , "OW", "HW","HOH","WAT",
            "F" , 
	        "Cl", "CL",
	        "Br", "BR",
	        "I" ,
	        "Li", "LI",
	        "Na", "NA",
            "K" ,
	        "Rb", "RB",
	        "Cs", "CS",
	        "Mg", "MG",
            "Tl", "TL",
            "Cu", "CU",
            "Ag", "AG",
            "Be", "BE",
            "Ni", "NI",
            "Pt", "PT",
            "Zn", "ZN",
            "Co", "CO",
            "Pd", "PD",
            "Cr", "CR",
            "Fe", "FE",
            "V" ,
            "Mn", "MN",
            "Hg", "HG",
            "Cd", "CD",
            "Yb", "YB",
            "Ca", "CA",
            "Sn", "SN",
            "Pb", "PB",
            "Eu", "EU",
            "Sr", "SR",
            "Sm", "SM",
            "Ba", "BA",
            "Ra", "RA",
            "Al", "AL",
            "In", "IN",
            "Y" ,
            "La", "LA",
            "Ce", "CE",
            "Pr", "PR",
            "Nd", "ND",
            "Gd", "GD",
            "Tb", "TB",
            "Dy", "DY",
            "Er", "ER",
            "Tm", "TM",
            "Lu", "LU",
            "Hf", "HF",
            "Zr", "ZR",
            "U" ,
            "Pu", "PU",
            "Th", "TH"  ]

# a map all metal (resi_name:atom_name)
Metal_map ={"LI" : "Li",
	        "NA" : "Na",
            "K"  : "K" ,
	        "RB" : "Rb",
	        "CS" : "Cs",
	        "MG" : "Mg",
            "TL" : "Tl",
            "CU" : "Cu",
            "AG" : "Ag",
            "BE" : "Be",
            "NI" : "Ni",
            "PT" : "Pt",
            "ZN" : "Zn",
            "CO" : "Co",
            "PD" : "Pd",
            "CR" : "Cr",
            "FE" : "Fe",
            "V"  : "V" ,
            "MN" : "Mn",
            "HG" : "Hg",
            "CD" : "Cd",
            "YB" : "Yb",
            "CA" : "Ca",
            "SN" : "Sn",
            "PB" : "Pb",
            "EU" : "Eu",
            "SR" : "Sr",
            "SM" : "Sm",
            "BA" : "Ba",
            "RA" : "Ra",
            "AL" : "Al",
            "IN" : "In",
            "Y"  : "Y" ,
            "LA" : "La",
            "CE" : "Ce",
            "PR" : "Pr",
            "ND" : "Nd",
            "GD" : "Gd",
            "TB" : "Tb",
            "DY" : "Dy",
            "ER" : "Er",
            "TM" : "Tm",
            "LU" : "Lu",
            "HF" : "Hf",
            "ZR" : "Zr",
            "U"  : "U" ,
            "PU" : "Pu",
            "TH" : "Th" }

# Potential coordination center: add upon discover. (resi_name:atom_name)
MetalCenter_map = { "MG" : "Mg",
                    "TL" : "Tl",
                    "CU" : "Cu",
                    "AG" : "Ag",
                    "BE" : "Be",
                    "NI" : "Ni",
                    "PT" : "Pt",
                    "ZN" : "Zn",
                    "CO" : "Co",
                    "PD" : "Pd",
                    "CR" : "Cr",
                    "FE" : "Fe",
                    "V"  : "V" ,
                    "MN" : "Mn",
                    "HG" : "Hg",
                    "CD" : "Cd",
                    "YB" : "Yb",
                    "CA" : "Ca",
                    "SN" : "Sn",
                    "PB" : "Pb",
                    "EU" : "Eu",
                    "SR" : "Sr",
                    "SM" : "Sm",
                    "BA" : "Ba",
                    "RA" : "Ra",
                    "AL" : "Al",
                    "IN" : "In",
                    "Y"  : "Y" ,
                    "LA" : "La",
                    "CE" : "Ce",
                    "PR" : "Pr",
                    "ND" : "Nd",
                    "GD" : "Gd",
                    "TB" : "Tb",
                    "DY" : "Dy",
                    "ER" : "Er",
                    "TM" : "Tm",
                    "LU" : "Lu",
                    "HF" : "Hf",
                    "ZR" : "Zr",
                    "U"  : "U" ,
                    "PU" : "Pu",
                    "TH" : "Th" }

# A map for element conversio, independent of the grammer.
# Amber: base on a Amber18 LEaP ff14SB output
Resi_Ele_map = {'Amber': {    'C' : 'C',
                              'CA' : 'C',
                              'CB' : 'C',
                              'CD' : 'C',
                              'CD1' : 'C',
                              'CD2' : 'C',
                              'CE' : 'C',
                              'CE1' : 'C',
                              'CE2' : 'C',
                              'CE3' : 'C',
                              'CG' : 'C',
                              'CG1' : 'C',
                              'CG2' : 'C',
                              'CH2' : 'C',
                              'CZ' : 'C',
                              'CZ2' : 'C',
                              'CZ3' : 'C',
                              'H' : 'H',
                              'H1' : 'H',
                              'H2' : 'H',
                              'H3' : 'H',
                              'HA' : 'H',
                              'HA2' : 'H',
                              'HA3' : 'H',
                              'HB' : 'H',
                              'HB1' : 'H',
                              'HB2' : 'H',
                              'HB3' : 'H',
                              'HD1' : 'H',
                              'HD11' : 'H',
                              'HD12' : 'H',
                              'HD13' : 'H',
                              'HD2' : 'H',
                              'HD21' : 'H',
                              'HD22' : 'H',
                              'HD23' : 'H',
                              'HD3' : 'H',
                              'HE' : 'H',
                              'HE1' : 'H',
                              'HE2' : 'H',
                              'HE21' : 'H',
                              'HE22' : 'H',
                              'HE3' : 'H',
                              'HG' : 'H',
                              'HG1' : 'H',
                              'HG11' : 'H',
                              'HG12' : 'H',
                              'HG13' : 'H',
                              'HG2' : 'H',
                              'HG21' : 'H',
                              'HG22' : 'H',
                              'HG23' : 'H',
                              'HG3' : 'H',
                              'HH' : 'H',
                              'HH11' : 'H',
                              'HH12' : 'H',
                              'HH2' : 'H',
                              'HH21' : 'H',
                              'HH22' : 'H',
                              'HZ' : 'H',
                              'HZ1' : 'H',
                              'HZ2' : 'H',
                              'HZ3' : 'H',
                              'N' : 'N',
                              'ND1' : 'N',
                              'ND2' : 'N',
                              'NE' : 'N',
                              'NE1' : 'N',
                              'NE2' : 'N',
                              'NH1' : 'N',
                              'NH2' : 'N',
                              'NZ' : 'N',
                              'O' : 'O',
                              'OD1' : 'O',
                              'OD2' : 'O',
                              'OE1' : 'O',
                              'OE2' : 'O',
                              'OG' : 'O',
                              'OG1' : 'O',
                              'OH' : 'O',
                              'OXT' : 'O',
                              'SD' : 'S',
                              'SG' : 'S',
                              "LI" : "Li",
                              "NA" : "Na",
                              "K"  : "K" ,
                              "RB" : "Rb",
                              "CS" : "Cs",
                              "MG" : "Mg",
                              "TL" : "Tl",
                              "CU" : "Cu",
                              "AG" : "Ag",
                              "BE" : "Be",
                              "NI" : "Ni",
                              "PT" : "Pt",
                              "ZN" : "Zn",
                              "CO" : "Co",
                              "PD" : "Pd",
                              "CR" : "Cr",
                              "FE" : "Fe",
                              "V"  : "V" ,
                              "MN" : "Mn",
                              "HG" : "Hg",
                              "CD" : "Cd",
                              "YB" : "Yb",
                              "CA" : "Ca",
                              "SN" : "Sn",
                              "PB" : "Pb",
                              "EU" : "Eu",
                              "SR" : "Sr",
                              "SM" : "Sm",
                              "BA" : "Ba",
                              "RA" : "Ra",
                              "AL" : "Al",
                              "IN" : "In",
                              "Y"  : "Y" ,
                              "LA" : "La",
                              "CE" : "Ce",
                              "PR" : "Pr",
                              "ND" : "Nd",
                              "GD" : "Gd",
                              "TB" : "Tb",
                              "DY" : "Dy",
                              "ER" : "Er",
                              "TM" : "Tm",
                              "LU" : "Lu",
                              "HF" : "Hf",
                              "ZR" : "Zr",
                              "U"  : "U" ,
                              "PU" : "Pu",
                              "TH" : "Th" }       }

# Potential coordination donor: add upon discover. (atom name - base on the atom type definition in the force field)
# ========= Side chain Heteroatoms (O,N,S) ==============
# Amber: base on a Amber18 LEaP ff14SB output

Donor_atom_list={'Amber': [   'NH2', 'NE', 'NH1',
                              'ND1', 'NE2',
                              'NZ',
                              'OD1', 'OD2',
                              'OE1', 'OE2',
                              'OG',
                              'OG1',
                              'ND2', 'OD1',
                              'OE1', 'NE2',
                              'SG',
                              'SD',
                              'OH',
                              'NE1'             ] } 


# A list for residues with ambiguous protonation state that have potential deprotonation
AmbProton_list = [  'ASH','ASP',
                    'CYS','CYM',
                    'GLH','GLU',
              'HIP','HIE',
                    'HID',
              'LYS','LYN',
                    'TYR','TYM',
              'ARG','AR0']

# a map of residue name of deprotonation {resi_name : (depro_resi_name, depro_proton_name), ...}
# atom name base on a Amber18 LEaP ff14SB output   
DeProton_map = {    'ASH' : ('ASP','HD2'),
                    'CYS' : ('CYM','HG' ),
                    'GLH' : ('GLU','HE2'),
              'HIP' : (('HIE', 'HD1'), ('HID', 'HE2')),
              'HID' : None,   # depending on the T_atom, no default method
              'HIE' : None,
              'LYS' : ('LYN','HZ1'),
                    'TYR' : ('TYM','HH'),
              'ARG' : ('AR0','HH22')}

NoProton_list = ['ASP', 'GLU', 'MET'] 

# reference: doi:10.1107/S0567739476001551 (element : radius)
Ionic_radious_map={ "N"  : 1.32, 
                    "O"  : 1.26, 
                    "S"  : 1.70, 
                    "Mg" : None, 
                    "Li" : None, 
                    "Tl" : None, 
                    "Cu" : None, 
                    "Ag" : None, 
                    "Be" : None, 
                    "Ni" : None, 
                    "Pt" : None, 
                    "Zn" : 0.88, 
                    "Co" : None, 
                    "Pd" : None, 
                    "Cr" : None, 
                    "Fe" : None, 
                    "V"  : None, 
                    "Mn" : None, 
                    "Hg" : None, 
                    "Cd" : None, 
                    "Yb" : None, 
                    "Ca" : None, 
                    "Sn" : None, 
                    "Pb" : None, 
                    "Eu" : None, 
                    "Sr" : None, 
                    "Sm" : None, 
                    "Ba" : None, 
                    "Ra" : None, 
                    "Al" : None, 
                    "In" : None, 
                    "Y"  : None, 
                    "La" : None, 
                    "Ce" : None, 
                    "Pr" : None, 
                    "Nd" : None, 
                    "Gd" : None, 
                    "Tb" : None, 
                    "Dy" : None, 
                    "Er" : None, 
                    "Tm" : None, 
                    "Lu" : None, 
                    "Hf" : None, 
                    "Zr" : None, 
                    "U"  : None, 
                    "Pu" : None, 
                    "Th" : None }

# reference:  doi:10.1021/jp8111556 (element : radius)
VDW_radious_map = { "N"  : 1.55, 
                    "O"  : 1.52, 
                    "S"  : 1.80, 
                    "K"  : None, 
                    "Rb" : None, 
                    "Cs" : None, 
                    "Mg" : None, 
                    "Tl" : None, 
                    "Cu" : None, 
                    "Ag" : None, 
                    "Be" : None, 
                    "Ni" : None, 
                    "Pt" : None, 
                    "Zn" : 1.39, 
                    "Co" : None, 
                    "Pd" : None, 
                    "Cr" : None, 
                    "Fe" : None, 
                    "V"  : None, 
                    "Mn" : None, 
                    "Hg" : None, 
                    "Cd" : None, 
                    "Yb" : None, 
                    "Ca" : None, 
                    "Sn" : None, 
                    "Pb" : None, 
                    "Eu" : None, 
                    "Sr" : None, 
                    "Sm" : None, 
                    "Ba" : None, 
                    "Ra" : None, 
                    "Al" : None, 
                    "In" : None, 
                    "Y"  : None, 
                    "La" : None, 
                    "Ce" : None, 
                    "Pr" : None, 
                    "Nd" : None, 
                    "Gd" : None, 
                    "Tb" : None, 
                    "Dy" : None, 
                    "Er" : None, 
                    "Tm" : None, 
                    "Lu" : None, 
                    "Hf" : None, 
                    "Zr" : None, 
                    "U"  : None, 
                    "Pu" : None, 
                    "Th" : None }

