name: enzyhtp
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4
  - biopandas
  - biopython
  - colorlog
  - openbabel
  - pdb2pqr
  - plum-dispatch=2.2.2
  - pymol-open-source=2.5.0=py39he03f1b4_6
  - pyvista
  - rdkit
  - requests
  - scipy
  - setuptools
  - goodvibes=3.2
  - periodictable
  - sympy
  - editdistance
  - scikit-learn
