name: enzyhtp
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4
  - biopandas
  - biopython
  - bottleneck
  - brotli-python
  - bs4
  - ca-certificates
  - charset-normalizer
  - colorlog
  - curl
  - importlib-resources
  - importlib_resources
  - kiwisolver
  - matplotlib-base
  - numpy
  - numpy-base
  - openbabel
  - pandas
  - pdb2pqr
  - pillow
  - pip
  - plum-dispatch
  - pymol-open-source
  - pyqt
  - pyqt5-sip
  - pytest
  - pyvista
  - rdkit
  - requests
  - scipy
  - setuptools
  - typing-extensions
  - typing_extensions
  - wheel
