#!/bin/bash
#SBATCH --nodes=1
#SBATCH --gres=gpu:nvidia_rtx_a4000:1
#SBATCH --job-name=AF2_EnzyHTP
#SBATCH --partition=interactive_gpu
#SBATCH --account=yang_lab_csb_iacc
#SBATCH --mem=24G
#SBATCH --time=30:00
#SBATCH --qos=debug_iacc
#SBATCH --export=NONE

# Script generated by EnzyHTP 2.0.0 in 2025-08-29 17:59:41

source /sb/apps/alphafold232/miniconda3/bin/activate af232
export LD_LIBRARY_PATH=/sb/apps/alphafold232/miniconda3/envs/af232/lib:$LD_LIBRARY_PATH

python /sb/apps/alphafold232/alphafold/run_alphafold.py --fasta_paths /panfs/accrepfs.vampire/home/shaoq1/bin/dev_test/EnzyHTP-refactor/test/_interface/work_dir/test_af2_output/seq_0.fasta --output_dir /panfs/accrepfs.vampire/home/shaoq1/bin/dev_test/EnzyHTP-refactor/test/_interface/work_dir/test_af2_output --data_dir /sb/apps/alphafold-data.230 --db_preset full_dbs --max_template_date 1900-01-01 --model_preset multimer --models_to_relax none --num_multimer_predictions_per_model 1 --use_precomputed_msas --uniref90_database_path /sb/apps/alphafold-data.230/uniref90/uniref90.fasta --mgnify_database_path /sb/apps/alphafold-data.230/mgnify/mgy_clusters_2022_05.fa --uniref30_database_path /sb/apps/alphafold-data.230/uniref30/UniRef30_2021_03 --bfd_database_path /sb/apps/alphafold-data.230/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt --template_mmcif_dir /panfs/accrepfs.vampire/home/shaoq1/bin/dev_test/EnzyHTP-refactor/test/_interface/data//dummy_af2_template_database/ --pdb_seqres_database_path /panfs/accrepfs.vampire/home/shaoq1/bin/dev_test/EnzyHTP-refactor/test/_interface/data//dummy_af2_template_database/dummy_fas.fas --uniprot_database_path /sb/apps/alphafold-data.230/uniprot/uniprot.fasta --obsolete_pdbs_path /panfs/accrepfs.vampire/home/shaoq1/bin/dev_test/EnzyHTP-refactor/test/_interface/data//dummy_af2_template_database/dummy_obsolete.dat --hhblits_binary_path /sb/apps/alphafold232/miniconda3/envs/af232/bin/hhblits --hhsearch_binary_path /sb/apps/alphafold232/miniconda3/envs/af232/bin/hhsearch --hmmbuild_binary_path /sb/apps/alphafold232/miniconda3/envs/af232/bin/hmmbuild --hmmsearch_binary_path /sb/apps/alphafold232/miniconda3/envs/af232/bin/hmmsearch --jackhmmer_binary_path /sb/apps/alphafold232/miniconda3/envs/af232/bin/jackhmmer --kalign_binary_path /sb/apps/alphafold232/miniconda3/envs/af232/bin/kalign --use_gpu_relax
