#!/usr/bin/env bash

# Store the initial working directory
initial_dir=$(pwd)

# Change the working directory to the parent directory of this script
cd "$(dirname "${BASH_SOURCE[0]}")"/..

# Set a default environment name
target_env_name=$CONDA_DEFAULT_ENV

# Function to display help message
show_help() {
    echo "Usage: ${0##*/} [-n|--name ENV_NAME]"
    echo
    echo "Install EnzyHTP to your conda environment."
    echo
    echo "   -n, --name    Specify the name of the conda environment. Defaults to current environment."
    echo "   -h, --help    Display this help and exit."
}

# Define the options
OPTS=$(getopt -o hn: --long help,name: -- "$@")

# Exit if the options have not been correctly specified.
if [ $? != 0 ]; then return; fi

# Extract options and their arguments into variables.
eval set -- "$OPTS"

while true; do
    case "$1" in
        -h|--help)
            show_help
            return;;
        -n|--name)
            target_env_name="$2"; shift 2;;
        --)
            shift; break;;
        *)
            break;;
    esac
done

# Get the conda version
CONDA_VERSION=$(conda --version | cut -d' ' -f2)
echo "Conda Version: $CONDA_VERSION"

# Remove the build directory if it exists
if [[ -d build ]]; then
    rm -r build;
fi

# Function to activate the conda environment
activate_env() {
    if type conda > /dev/null 2>&1; then
        echo "Activating environment using conda"
        conda activate "$target_env_name"
    else
        echo "Activating environment using source"
        source activate "$target_env_name"
    fi
}

# Function for yes/no prompt, called when the target environment is 'base'.
prompt_yes_no() {
    while true; do
        read -p "$1 (yes/no): " yn
        case $yn in
            [Yy]* ) break;;
            [Nn]* ) return;;
            * ) echo "Please answer yes or no.";;
        esac
    done
}

# Function to check if the environment exists and create it if not
check_and_create_env() {
    if ! conda info --envs | grep "$target_env_name" > /dev/null; then
        echo "Environment $target_env_name does not exist. Creating..."
        conda create -n "$target_env_name" python=3.9 --yes
    else
        echo "Environment $target_env_name exists."
    fi
}

# Function to update the conda environment
update_env() {
    echo "Updating conda environment: $target_env_name"
    conda env update -n "$target_env_name" --file environment.yml
    activate_env
    dev-tools/pip-install
}

# Check current conda environment and extract environment name.
current_env_path=$(conda info --json | grep "\"default_prefix\":" | awk '{print $2}' | tr -d '",')
current_env_name=$(basename "$current_env_path")

echo "Installing EnzyHTP to Conda environment: $target_env_name"


# Check if the user is about to install in the base environment
if [[ "$target_env_name" == "base" ]]; then
    prompt_yes_no "You are about to install EnzyHTP in the base environment. Are you sure you want to continue?"
fi

# Compare current environment with env_name
if [ "$current_env_name" = "$target_env_name" ]; then
    echo "Deactivating current environment $current_env_name"
    conda deactivate
    update_env
else
    # Check and create environment if necessary.
    check_and_create_env

    # After checking, perform update.
    update_env
    conda deactivate
fi

cd $initial_dir
