#!/usr/bin/env bash


PIP_VERSION=$(pip --version | cut -d' ' -f2)

echo $PIP_VERSION

if [[ -d build ]]; then
    rm -rf build;

fi

versions=$(printf "%s\n21.3\n"  $PIP_VERSION )


if [[ $versions == $(echo $versions | sort ) ]]; then

    PYTHONNOUSERSITE=1 pip install . --use-feature=in-tree-build


else

    PYTHONNOUSERSITE=1 pip install . 
fi


