#!/bin/bash
#SBATCH --core_type=cpu
#SBATCH --node_cores=24
#SBATCH --job_name=job_name
#SBATCH --partition=production
#SBATCH --mem_per_core=4G
#SBATCH --walltime=24:00:00
#SBATCH --account=xxx

# Script generated by EnzyHTP in 2022-04-21 00:16:19

module load GCC/6.4.0-2.28  OpenMPI/2.1.1
module load Amber/17-Python-2.7.14
module unload Python/2.7.14 numpy/1.13.1-Python-2.7.14

g16 < xxx.gjf > xxx.out
