"""Stores mappers and testing functions for residue information. Much of this functionality is later used in 
NOTE: using PDB style atom names as official atom naming scheme in EnzyHTP. Make atom name convertor for other
    naming scheme.

Author: Qianzhen (QZ) Shao <shaoqz@icloud.com>
Author: Chris Jurich <chris.jurich@vanderbilt.edu>
Date: 2022-03-19
"""

from typing import List, Set, Dict, Union
from ..core import InvalidResidueCode, _LOGGER

# yapf: disable

AA_LIST: List[str] = ["R","H","K","D","E","S","T","N","Q","C","G","P","A","V","I","L","M","F","Y","W","U"]
"""Capitalized list of all one-letter amino acid names."""

THREE_LETTER_AA_MAPPER: Dict[str, str] = {
        "ALA": "A",
        "ARG": "R",
        "ASH": "N",
        "ASN": "N",
        "ASP": "D",
        "CYS": "C",
        "CYM": "C",
        "CYX": "C",
        "GLN": "Q",
        "GLH": "E",
        "GLU": "E",
        "GLY": "G",
        "HID": "H",
        "HIE": "H",
        "HIP": "H",
        "HIS": "H",
        "ILE": "I",
        "LEU": "L",
        "LYN": "K",
        "LYS": "K",
        "MET": "M",
        "PHE": "F",
        "PRO": "P",
        "SEC": "U",
        "SER": "S",
        "THR": "T",
        "TRP": "W",
        "TYR": "Y",
        "VAL": "V"
} #TODO(shaoqz): @imp2 add related to canonical in the name
"""Contains mapping of all amino acids codes, with key value pairs of (three letter code, one letter code). Should NOT be called directly for code conversion. Instead used enzy_htp.chemical.residue.convert_to_one_letter()"""

ONE_LETTER_AA_MAPPER: Dict[str, str] = {
        "A": "ALA",
        "C": "CYS",
        "D": "ASP",
        "E": "GLU",
        "F": "PHE",
        "G": "GLY",
        "H": "HIS",
        "I": "ILE",
        "K": "LYS",
        "L": "LEU",
        "M": "MET",
        "N": "ASN",
        "P": "PRO",
        "Q": "GLN",
        "R": "ARG",
        "S": "SER",
        "T": "THR",
        "U": "SEC",
        "V": "VAL",
        "W": "TRP",
        "Y": "TYR"
}
"""Contains mapping of all amino acids codes, with key value pairs of (one letter code, three letter code). Should NOT be called directly for code conversion. Instead used enzy_htp.chemical.residue.convert_to_three_letter()"""

ONE_LETTER_CAA_MAPPER: Dict[str, str] = {
        "A": "ALA",
        "C": "CYS",
        "D": "ASP",
        "E": "GLU",
        "F": "PHE",
        "G": "GLY",
        "H": "HIS",
        "I": "ILE",
        "K": "LYS",
        "L": "LEU",
        "M": "MET",
        "N": "ASN",
        "P": "PRO",
        "Q": "GLN",
        "R": "ARG",
        "S": "SER",
        "T": "THR",
        "V": "VAL",
        "W": "TRP",
        "Y": "TYR"
}
"""Contains mapping of all canonical amino acids codes, with key value pairs of (one letter code, three letter code). Should NOT be called directly for code conversion. Instead used enzy_htp.chemical.residue.convert_to_one_letter()"""

THREE_TO_THREE_LETTER_CAA_MAPPER: Dict[str, str] = {
        "ALA": "ALA",
        "ARG": "ARG",
        "ASH": "ASN",
        "ASN": "ASN",
        "ASP": "ASP",
        "CYS": "CYS",
        "CYM": "CYS",
        "CYX": "CYS",
        "GLN": "GLN",
        "GLH": "GLU",
        "GLU": "GLU",
        "GLY": "GLY",
        "HID": "HIS",
        "HIE": "HIS",
        "HIP": "HIS",
        "HIS": "HIS",
        "ILE": "ILE",
        "LEU": "LEU",
        "LYN": "LYS",
        "LYS": "LYS",
        "MET": "MET",
        "PHE": "PHE",
        "PRO": "PRO",
        "SEC": "SEC",
        "SER": "SER",
        "THR": "THR",
        "TRP": "TRP",
        "TYR": "TYR",
        "VAL": "VAL"
}
"""Contains mapping of all canonical amino acids codes, with key value pairs of
(three letter code, canonicalized three letter code). Should NOT be called directly
for code conversion. Instead used enzy_htp.chemical.residue.convert_to_canoncial_three_letter()"""

RESIDUE_ELEMENT_MAP: Dict[str, Dict[str, str]] = {
                "Amber": {    "C" : "C",
                              "CA" : "C",
                              "CB" : "C",
                              "CD" : "C",
                              "CD1" : "C",
                              "CD2" : "C",
                              "CE" : "C",
                              "CE1" : "C",
                              "CE2" : "C",
                              "CE3" : "C",
                              "CG" : "C",
                              "CG1" : "C",
                              "CG2" : "C",
                              "CH2" : "C",
                              "CZ" : "C",
                              "CZ2" : "C",
                              "CZ3" : "C",
                              "H" : "H",
                              "H1" : "H",
                              "H2" : "H",
                              "H3" : "H",
                              "HA" : "H",
                              "HA2" : "H",
                              "HA3" : "H",
                              "HB" : "H",
                              "HB1" : "H",
                              "HB2" : "H",
                              "HB3" : "H",
                              "HD1" : "H",
                              "HD11" : "H",
                              "HD12" : "H",
                              "HD13" : "H",
                              "HD2" : "H",
                              "HD21" : "H",
                              "HD22" : "H",
                              "HD23" : "H",
                              "HD3" : "H",
                              "HE" : "H",
                              "HE1" : "H",
                              "HE2" : "H",
                              "HE21" : "H",
                              "HE22" : "H",
                              "HE3" : "H",
                              "HG" : "H",
                              "HG1" : "H",
                              "HG11" : "H",
                              "HG12" : "H",
                              "HG13" : "H",
                              "HG2" : "H",
                              "HG21" : "H",
                              "HG22" : "H",
                              "HG23" : "H",
                              "HG3" : "H",
                              "HH" : "H",
                              "HH11" : "H",
                              "HH12" : "H",
                              "HH2" : "H",
                              "HH21" : "H",
                              "HH22" : "H",
                              "HZ" : "H",
                              "HZ1" : "H",
                              "HZ2" : "H",
                              "HZ3" : "H",
                              "N" : "N",
                              "ND1" : "N",
                              "ND2" : "N",
                              "NE" : "N",
                              "NE1" : "N",
                              "NE2" : "N",
                              "NH1" : "N",
                              "NH2" : "N",
                              "NZ" : "N",
                              "O" : "O",
                              "OD1" : "O",
                              "OD2" : "O",
                              "OE1" : "O",
                              "OE2" : "O",
                              "OG" : "O",
                              "OG1" : "O",
                              "OH" : "O",
                              "OXT" : "O",
                              "SD" : "S",
                              "SG" : "S",
                              "LI" : "Li",
                              "NA" : "Na",
                              "K"  : "K" ,
                              "RB" : "Rb",
                              "CS" : "Cs",
                              "MG" : "Mg",
                              "TL" : "Tl",
                              "CU" : "Cu",
                              "AG" : "Ag",
                              "BE" : "Be",
                              "NI" : "Ni",
                              "PT" : "Pt",
                              "ZN" : "Zn",
                              "CO" : "Co",
                              "PD" : "Pd",
                              "CR" : "Cr",
                              "FE" : "Fe",
                              "V"  : "V" ,
                              "MN" : "Mn",
                              "YB" : "Yb",
                              "SN" : "Sn",
                              "PB" : "Pb",
                              "EU" : "Eu",
                              "SR" : "Sr",
                              "SM" : "Sm",
                              "BA" : "Ba",
                              "RA" : "Ra",
                              "AL" : "Al",
                              "IN" : "In",
                              "Y"  : "Y" ,
                              "LA" : "La",
                              "PR" : "Pr",
                              "ND" : "Nd",
                              "GD" : "Gd",
                              "TB" : "Tb",
                              "DY" : "Dy",
                              "ER" : "Er",
                              "TM" : "Tm",
                              "LU" : "Lu",
                              "HF" : "Hf",
                              "ZR" : "Zr",
                              "U"  : "U" ,
                              "PU" : "Pu",
                              "TH" : "Th" }
}
"""Mapper that shows element names for alternative names of atoms. Key value structure is (force field name, (atom mapper)), where atom mapper is an additional
mapper that maps altered atom names to base atom names. Currently only defined for "Amber".

Example usage:

>>> initial_atom_name = "CA"
>>> RESIDUE_ELEMENT_MAP["Amber"][initial_atom_name] TODO also remove those ff keys
"C"

"""

RESIDUE_CONNECTIVITY_MAP: Dict[str, Dict[str, List[str]]] = {
                  "ALA": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB1", "HB2", "HB3"], "HB1": ["CB"], "HB2": ["CB"], "HB3": ["CB"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "ARG": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "HG2", "HG3", "CD"], "HG2": ["CG"], "HG3": ["CG"], "CD": ["CG", "HD2", "HD3", "NE"], "HD2": ["CD"], "HD3": ["CD"], "NE": ["CD", "HE", "CZ"], "HE": ["NE"], "CZ": ["NE", "NH1", "NH2"], "NH1": ["CZ", "HH11", "HH12"], "HH11": ["NH1"], "HH12": ["NH1"], "NH2": ["CZ", "HH21", "HH22"], "HH21": ["NH2"], "HH22": ["NH2"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "ASH": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "OD1", "OD2"], "OD1": ["CG"], "OD2": ["CG", "HD2"], "HD2": ["OD2"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "ASN": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "OD1", "ND2"], "OD1": ["CG"], "ND2": ["CG", "HD21", "HD22"], "HD21": ["ND2"], "HD22": ["ND2"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "ASP": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "OD1", "OD2"], "OD1": ["CG"], "OD2": ["CG"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "CYM": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB3", "HB2", "SG"], "HB3": ["CB"], "HB2": ["CB"], "SG": ["CB"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "CYS": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "SG"], "HB2": ["CB"], "HB3": ["CB"], "SG": ["CB", "HG"], "HG": ["SG"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "CYX": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "SG"], "HB2": ["CB"], "HB3": ["CB"], "SG": ["CB"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "GLH": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "HG2", "HG3", "CD"], "HG2": ["CG"], "HG3": ["CG"], "CD": ["CG", "OE1", "OE2"], "OE1": ["CD"], "OE2": ["CD", "HE2"], "HE2": ["OE2"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "GLN": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "HG2", "HG3", "CD"], "HG2": ["CG"], "HG3": ["CG"], "CD": ["CG", "OE1", "NE2"], "OE1": ["CD"], "NE2": ["CD", "HE21", "HE22"], "HE21": ["NE2"], "HE22": ["NE2"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "GLU": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "HG2", "HG3", "CD"], "HG2": ["CG"], "HG3": ["CG"], "CD": ["CG", "OE1", "OE2"], "OE1": ["CD"], "OE2": ["CD"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "GLY": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA2", "HA3", "C"], "HA2": ["CA"], "HA3": ["CA"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "HID": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "ND1", "CD2"], "ND1": ["CG", "HD1", "CE1"], "HD1": ["ND1"], "CE1": ["ND1", "HE1", "NE2"], "HE1": ["CE1"], "NE2": ["CE1", "CD2"], "CD2": ["CG", "NE2", "HD2"], "HD2": ["CD2"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "HIE": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "ND1", "CD2"], "ND1": ["CG", "CE1"], "CE1": ["ND1", "HE1", "NE2"], "HE1": ["CE1"], "NE2": ["CE1", "HE2", "CD2"], "HE2": ["NE2"], "CD2": ["CG", "NE2", "HD2"], "HD2": ["CD2"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "HIP": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "ND1", "CD2"], "ND1": ["CG", "HD1", "CE1"], "HD1": ["ND1"], "CE1": ["ND1", "HE1", "NE2"], "HE1": ["CE1"], "NE2": ["CE1", "HE2", "CD2"], "HE2": ["NE2"], "CD2": ["CG", "NE2", "HD2"], "HD2": ["CD2"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "HYP": {"N": ["CD", "CA", "-1C"], "CD": ["N", "HD22", "HD23", "CG"], "HD22": ["CD"], "HD23": ["CD"], "CG": ["CD", "HG", "OD1", "CB"], "HG": ["CG"], "OD1": ["CG", "HD1"], "HD1": ["OD1"], "CB": ["CG", "HB2", "HB3", "CA"], "HB2": ["CB"], "HB3": ["CB"], "CA": ["N", "CB", "HA", "C"], "HA": ["CA"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "ILE": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB", "CG2", "CG1"], "HB": ["CB"], "CG2": ["CB", "HG21", "HG22", "HG23"], "HG21": ["CG2"], "HG22": ["CG2"], "HG23": ["CG2"], "CG1": ["CB", "HG12", "HG13", "CD1"], "HG12": ["CG1"], "HG13": ["CG1"], "CD1": ["CG1", "HD11", "HD12", "HD13"], "HD11": ["CD1"], "HD12": ["CD1"], "HD13": ["CD1"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "LEU": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "HG", "CD1", "CD2"], "HG": ["CG"], "CD1": ["CG", "HD11", "HD12", "HD13"], "HD11": ["CD1"], "HD12": ["CD1"], "HD13": ["CD1"], "CD2": ["CG", "HD21", "HD22", "HD23"], "HD21": ["CD2"], "HD22": ["CD2"], "HD23": ["CD2"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "LYN": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "HG2", "HG3", "CD"], "HG2": ["CG"], "HG3": ["CG"], "CD": ["CG", "HD2", "HD3", "CE"], "HD2": ["CD"], "HD3": ["CD"], "CE": ["CD", "HE2", "HE3", "NZ"], "HE2": ["CE"], "HE3": ["CE"], "NZ": ["CE", "HZ2", "HZ3"], "HZ2": ["NZ"], "HZ3": ["NZ"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "LYS": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "HG2", "HG3", "CD"], "HG2": ["CG"], "HG3": ["CG"], "CD": ["CG", "HD2", "HD3", "CE"], "HD2": ["CD"], "HD3": ["CD"], "CE": ["CD", "HE2", "HE3", "NZ"], "HE2": ["CE"], "HE3": ["CE"], "NZ": ["CE", "HZ1", "HZ2", "HZ3"], "HZ1": ["NZ"], "HZ2": ["NZ"], "HZ3": ["NZ"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "MET": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "HG2", "HG3", "SD"], "HG2": ["CG"], "HG3": ["CG"], "SD": ["CG", "CE"], "CE": ["SD", "HE1", "HE2", "HE3"], "HE1": ["CE"], "HE2": ["CE"], "HE3": ["CE"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "PHE": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "CD1", "CD2"], "CD1": ["CG", "HD1", "CE1"], "HD1": ["CD1"], "CE1": ["CD1", "HE1", "CZ"], "HE1": ["CE1"], "CZ": ["CE1", "HZ", "CE2"], "HZ": ["CZ"], "CE2": ["CZ", "HE2", "CD2"], "HE2": ["CE2"], "CD2": ["CG", "CE2", "HD2"], "HD2": ["CD2"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "PRO": {"N": ["CD", "CA", "-1C"], "CD": ["N", "HD2", "HD3", "CG"], "HD2": ["CD"], "HD3": ["CD"], "CG": ["CD", "HG2", "HG3", "CB"], "HG2": ["CG"], "HG3": ["CG"], "CB": ["CG", "HB2", "HB3", "CA"], "HB2": ["CB"], "HB3": ["CB"], "CA": ["N", "CB", "HA", "C"], "HA": ["CA"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "SER": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "OG"], "HB2": ["CB"], "HB3": ["CB"], "OG": ["CB", "HG"], "HG": ["OG"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "THR": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB", "CG2", "OG1"], "HB": ["CB"], "CG2": ["CB", "HG21", "HG22", "HG23"], "HG21": ["CG2"], "HG22": ["CG2"], "HG23": ["CG2"], "OG1": ["CB", "HG1"], "HG1": ["OG1"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "TRP": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "CD1", "CD2"], "CD1": ["CG", "HD1", "NE1"], "HD1": ["CD1"], "NE1": ["CD1", "HE1", "CE2"], "HE1": ["NE1"], "CE2": ["NE1", "CZ2", "CD2"], "CZ2": ["CE2", "HZ2", "CH2"], "HZ2": ["CZ2"], "CH2": ["CZ2", "HH2", "CZ3"], "HH2": ["CH2"], "CZ3": ["CH2", "HZ3", "CE3"], "HZ3": ["CZ3"], "CE3": ["CZ3", "HE3", "CD2"], "HE3": ["CE3"], "CD2": ["CG", "CE2", "CE3"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "TYR": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "CD1", "CD2"], "CD1": ["CG", "HD1", "CE1"], "HD1": ["CD1"], "CE1": ["CD1", "HE1", "CZ"], "HE1": ["CE1"], "CZ": ["CE1", "OH", "CE2"], "OH": ["CZ", "HH"], "HH": ["OH"], "CE2": ["CZ", "HE2", "CD2"], "HE2": ["CE2"], "CD2": ["CG", "CE2", "HD2"], "HD2": ["CD2"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "VAL": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB", "CG1", "CG2"], "HB": ["CB"], "CG1": ["CB", "HG11", "HG12", "HG13"], "HG11": ["CG1"], "HG12": ["CG1"], "HG13": ["CG1"], "CG2": ["CB", "HG21", "HG22", "HG23"], "HG21": ["CG2"], "HG22": ["CG2"], "HG23": ["CG2"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                  "WAT": {"O": ["H1", "H2"], "H1":["O"], "H2": ["O"]},
                  "HOH": {"O": ["H1", "H2"], "H1":["O"], "H2": ["O"]}
}
"""dict() that maps the connectivity of atom's based on their parent residue and atom identity.
(key, value) pairs are (3-letter AA name, connector), where connector is another dict() with 
(key, value) pairs of (atom name, list of connected atoms)."""

RESIDUE_CONNECTIVITY_MAP_CTERMINAL: Dict[str, Dict[str, List[str]]] = {
                        "ALA": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB1", "HB2", "HB3"], "HB1": ["CB"], "HB2": ["CB"], "HB3": ["CB"], "C": ["CA", "O", "OXT"], "O": ["C"], "OXT": ["C"]},
                        "ARG": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "HG2", "HG3", "CD"], "HG2": ["CG"], "HG3": ["CG"], "CD": ["CG", "HD2", "HD3", "NE"], "HD2": ["CD"], "HD3": ["CD"], "NE": ["CD", "HE", "CZ"], "HE": ["NE"], "CZ": ["NE", "NH1", "NH2"], "NH1": ["CZ", "HH11", "HH12"], "HH11": ["NH1"], "HH12": ["NH1"], "NH2": ["CZ", "HH21", "HH22"], "HH21": ["NH2"], "HH22": ["NH2"], "C": ["CA", "O", "OXT"], "O": ["C"], "OXT": ["C"]},
                        "ASN": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "OD1", "ND2"], "OD1": ["CG"], "ND2": ["CG", "HD21", "HD22"], "HD21": ["ND2"], "HD22": ["ND2"], "C": ["CA", "O", "OXT"], "O": ["C"], "OXT": ["C"]},
                        "ASP": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "OD1", "OD2"], "OD1": ["CG"], "OD2": ["CG"], "C": ["CA", "O", "OXT"], "O": ["C"], "OXT": ["C"]},
                        "CYS": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "SG"], "HB2": ["CB"], "HB3": ["CB"], "SG": ["CB", "HG"], "HG": ["SG"], "C": ["CA", "O", "OXT"], "O": ["C"], "OXT": ["C"]},
                        "CYX": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "SG"], "HB2": ["CB"], "HB3": ["CB"], "SG": ["CB"], "C": ["CA", "O", "OXT"], "O": ["C"], "OXT": ["C"]},
                        "GLN": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "HG2", "HG3", "CD"], "HG2": ["CG"], "HG3": ["CG"], "CD": ["CG", "OE1", "NE2"], "OE1": ["CD"], "NE2": ["CD", "HE21", "HE22"], "HE21": ["NE2"], "HE22": ["NE2"], "C": ["CA", "O", "OXT"], "O": ["C"], "OXT": ["C"]},
                        "GLU": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "HG2", "HG3", "CD"], "HG2": ["CG"], "HG3": ["CG"], "CD": ["CG", "OE1", "OE2"], "OE1": ["CD"], "OE2": ["CD"], "C": ["CA", "O", "OXT"], "O": ["C"], "OXT": ["C"]},
                        "GLY": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA2", "HA3", "C"], "HA2": ["CA"], "HA3": ["CA"], "C": ["CA", "O", "OXT"], "O": ["C"], "OXT": ["C"]},
                        "HID": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "ND1", "CD2"], "ND1": ["CG", "HD1", "CE1"], "HD1": ["ND1"], "CE1": ["ND1", "HE1", "NE2"], "HE1": ["CE1"], "NE2": ["CE1", "CD2"], "CD2": ["CG", "NE2", "HD2"], "HD2": ["CD2"], "C": ["CA", "O", "OXT"], "O": ["C"], "OXT": ["C"]},
                        "HIE": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "ND1", "CD2"], "ND1": ["CG", "CE1"], "CE1": ["ND1", "HE1", "NE2"], "HE1": ["CE1"], "NE2": ["CE1", "HE2", "CD2"], "HE2": ["NE2"], "CD2": ["CG", "NE2", "HD2"], "HD2": ["CD2"], "C": ["CA", "O", "OXT"], "O": ["C"], "OXT": ["C"]},
                        "HIP": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "ND1", "CD2"], "ND1": ["CG", "HD1", "CE1"], "HD1": ["ND1"], "CE1": ["ND1", "HE1", "NE2"], "HE1": ["CE1"], "NE2": ["CE1", "HE2", "CD2"], "HE2": ["NE2"], "CD2": ["CG", "NE2", "HD2"], "HD2": ["CD2"], "C": ["CA", "O", "OXT"], "O": ["C"], "OXT": ["C"]},
                        "HYP": {"N": ["CD", "CA", "-1C"], "CD": ["N", "HD22", "HD23", "CG"], "HD22": ["CD"], "HD23": ["CD"], "CG": ["CD", "HG", "OD1", "CB"], "HG": ["CG"], "OD1": ["CG", "HD1"], "HD1": ["OD1"], "CB": ["CG", "HB2", "HB3", "CA"], "HB2": ["CB"], "HB3": ["CB"], "CA": ["N", "CB", "HA", "C"], "HA": ["CA"], "C": ["CA", "O", "OXT"], "O": ["C"], "OXT": ["C"]},
                        "ILE": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB", "CG2", "CG1"], "HB": ["CB"], "CG2": ["CB", "HG21", "HG22", "HG23"], "HG21": ["CG2"], "HG22": ["CG2"], "HG23": ["CG2"], "CG1": ["CB", "HG12", "HG13", "CD1"], "HG12": ["CG1"], "HG13": ["CG1"], "CD1": ["CG1", "HD11", "HD12", "HD13"], "HD11": ["CD1"], "HD12": ["CD1"], "HD13": ["CD1"], "C": ["CA", "O", "OXT"], "O": ["C"], "OXT": ["C"]},
                        "LEU": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "HG", "CD1", "CD2"], "HG": ["CG"], "CD1": ["CG", "HD11", "HD12", "HD13"], "HD11": ["CD1"], "HD12": ["CD1"], "HD13": ["CD1"], "CD2": ["CG", "HD21", "HD22", "HD23"], "HD21": ["CD2"], "HD22": ["CD2"], "HD23": ["CD2"], "C": ["CA", "O", "OXT"], "O": ["C"], "OXT": ["C"]},
                        "LYS": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "HG2", "HG3", "CD"], "HG2": ["CG"], "HG3": ["CG"], "CD": ["CG", "HD2", "HD3", "CE"], "HD2": ["CD"], "HD3": ["CD"], "CE": ["CD", "HE2", "HE3", "NZ"], "HE2": ["CE"], "HE3": ["CE"], "NZ": ["CE", "HZ1", "HZ2", "HZ3"], "HZ1": ["NZ"], "HZ2": ["NZ"], "HZ3": ["NZ"], "C": ["CA", "O", "OXT"], "O": ["C"], "OXT": ["C"]},
                        "MET": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "HG2", "HG3", "SD"], "HG2": ["CG"], "HG3": ["CG"], "SD": ["CG", "CE"], "CE": ["SD", "HE1", "HE2", "HE3"], "HE1": ["CE"], "HE2": ["CE"], "HE3": ["CE"], "C": ["CA", "O", "OXT"], "O": ["C"], "OXT": ["C"]},
                        "PHE": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "CD1", "CD2"], "CD1": ["CG", "HD1", "CE1"], "HD1": ["CD1"], "CE1": ["CD1", "HE1", "CZ"], "HE1": ["CE1"], "CZ": ["CE1", "HZ", "CE2"], "HZ": ["CZ"], "CE2": ["CZ", "HE2", "CD2"], "HE2": ["CE2"], "CD2": ["CG", "CE2", "HD2"], "HD2": ["CD2"], "C": ["CA", "O", "OXT"], "O": ["C"], "OXT": ["C"]},
                        "PRO": {"N": ["CD", "CA", "-1C"], "CD": ["N", "HD2", "HD3", "CG"], "HD2": ["CD"], "HD3": ["CD"], "CG": ["CD", "HG2", "HG3", "CB"], "HG2": ["CG"], "HG3": ["CG"], "CB": ["CG", "HB2", "HB3", "CA"], "HB2": ["CB"], "HB3": ["CB"], "CA": ["N", "CB", "HA", "C"], "HA": ["CA"], "C": ["CA", "O", "OXT"], "O": ["C"], "OXT": ["C"]},
                        "SER": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "OG"], "HB2": ["CB"], "HB3": ["CB"], "OG": ["CB", "HG"], "HG": ["OG"], "C": ["CA", "O", "OXT"], "O": ["C"], "OXT": ["C"]},
                        "THR": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB", "CG2", "OG1"], "HB": ["CB"], "CG2": ["CB", "HG21", "HG22", "HG23"], "HG21": ["CG2"], "HG22": ["CG2"], "HG23": ["CG2"], "OG1": ["CB", "HG1"], "HG1": ["OG1"], "C": ["CA", "O", "OXT"], "O": ["C"], "OXT": ["C"]},
                        "TRP": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "CD1", "CD2"], "CD1": ["CG", "HD1", "NE1"], "HD1": ["CD1"], "NE1": ["CD1", "HE1", "CE2"], "HE1": ["NE1"], "CE2": ["NE1", "CZ2", "CD2"], "CZ2": ["CE2", "HZ2", "CH2"], "HZ2": ["CZ2"], "CH2": ["CZ2", "HH2", "CZ3"], "HH2": ["CH2"], "CZ3": ["CH2", "HZ3", "CE3"], "HZ3": ["CZ3"], "CE3": ["CZ3", "HE3", "CD2"], "HE3": ["CE3"], "CD2": ["CG", "CE2", "CE3"], "C": ["CA", "O", "OXT"], "O": ["C"], "OXT": ["C"]},
                        "TYR": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "CD1", "CD2"], "CD1": ["CG", "HD1", "CE1"], "HD1": ["CD1"], "CE1": ["CD1", "HE1", "CZ"], "HE1": ["CE1"], "CZ": ["CE1", "OH", "CE2"], "OH": ["CZ", "HH"], "HH": ["OH"], "CE2": ["CZ", "HE2", "CD2"], "HE2": ["CE2"], "CD2": ["CG", "CE2", "HD2"], "HD2": ["CD2"], "C": ["CA", "O", "OXT"], "O": ["C"], "OXT": ["C"]},
                        "VAL": {"N": ["H", "CA", "-1C"], "H": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB", "CG1", "CG2"], "HB": ["CB"], "CG1": ["CB", "HG11", "HG12", "HG13"], "HG11": ["CG1"], "HG12": ["CG1"], "HG13": ["CG1"], "CG2": ["CB", "HG21", "HG22", "HG23"], "HG21": ["CG2"], "HG22": ["CG2"], "HG23": ["CG2"], "C": ["CA", "O", "OXT"], "O": ["C"], "OXT": ["C"]},
                        "NHE": {"N": ["HN1", "HN2", "-1C"], "HN1": ["N"], "HN2": ["N"]},
                        "NME": {"N": ["H", "CH3", "-1C"], "H": ["N"], "CH3": ["N", "HH31", "HH32", "HH33"], "HH31": ["CH3"], "HH32": ["CH3"], "HH33": ["CH3"]}
}
"""dict() that maps the connectivity of atom's based on their parent residue and atom identity.
(key, value) pairs are (3-letter AA name, connector), where connector is another dict() with 
(key, value) pairs of (atom name, list of connected atoms). Similar to RESIDUE_CONNECTIVITY_MAP
except has the mappings for the C-terminal version of each residue."""

RESIDUE_CTERMINAL_ATOM_LIST: Dict[str, List[str]] = {
                        "ALA": ["N", "H", "CA", "HA", "CB", "HB1", "HB2", "HB3", "C", "O", "OXT"],
                        "ARG": ["N", "H", "CA", "HA", "CB", "HB2", "HB3", "CG", "HG2", "HG3", "CD", "HD2", "HD3", "NE", "HE", "CZ", "NH1", "HH11", "HH12", "NH2", "HH21", "HH22", "C", "O", "OXT"],
                        "ASN": ["N", "H", "CA", "HA", "CB", "HB2", "HB3", "CG", "OD1", "ND2", "HD21", "HD22", "C", "O", "OXT"],
                        "ASP": ["N", "H", "CA", "HA", "CB", "HB2", "HB3", "CG", "OD1", "OD2", "C", "O", "OXT"],
                        "CYS": ["N", "H", "CA", "HA", "CB", "HB2", "HB3", "SG", "HG", "C", "O", "OXT"],
                        "CYX": ["N", "H", "CA", "HA", "CB", "HB2", "HB3", "SG", "C", "O", "OXT"],
                        "GLN": ["N", "H", "CA", "HA", "CB", "HB2", "HB3", "CG", "HG2", "HG3", "CD", "OE1", "NE2", "HE21", "HE22", "C", "O", "OXT"],
                        "GLU": ["N", "H", "CA", "HA", "CB", "HB2", "HB3", "CG", "HG2", "HG3", "CD", "OE1", "OE2", "C", "O", "OXT"],
                        "GLY": ["N", "H", "CA", "HA2", "HA3", "C", "O", "OXT"],
                        "HID": ["N", "H", "CA", "HA", "CB", "HB2", "HB3", "CG", "ND1", "HD1", "CE1", "HE1", "NE2", "CD2", "HD2", "C", "O", "OXT"],
                        "HIE": ["N", "H", "CA", "HA", "CB", "HB2", "HB3", "CG", "ND1", "CE1", "HE1", "NE2", "HE2", "CD2", "HD2", "C", "O", "OXT"],
                        "HIP": ["N", "H", "CA", "HA", "CB", "HB2", "HB3", "CG", "ND1", "HD1", "CE1", "HE1", "NE2", "HE2", "CD2", "HD2", "C", "O", "OXT"],
                        "HYP": ["N", "CD", "HD22", "HD23", "CG", "HG", "OD1", "HD1", "CB", "HB2", "HB3", "CA", "HA", "C", "O", "OXT"],
                        "ILE": ["N", "H", "CA", "HA", "CB", "HB", "CG2", "HG21", "HG22", "HG23", "CG1", "HG12", "HG13", "CD1", "HD11", "HD12", "HD13", "C", "O", "OXT"],
                        "LEU": ["N", "H", "CA", "HA", "CB", "HB2", "HB3", "CG", "HG", "CD1", "HD11", "HD12", "HD13", "CD2", "HD21", "HD22", "HD23", "C", "O", "OXT"],
                        "LYS": ["N", "H", "CA", "HA", "CB", "HB2", "HB3", "CG", "HG2", "HG3", "CD", "HD2", "HD3", "CE", "HE2", "HE3", "NZ", "HZ1", "HZ2", "HZ3", "C", "O", "OXT"],
                        "MET": ["N", "H", "CA", "HA", "CB", "HB2", "HB3", "CG", "HG2", "HG3", "SD", "CE", "HE1", "HE2", "HE3", "C", "O", "OXT"],
                        "PHE": ["N", "H", "CA", "HA", "CB", "HB2", "HB3", "CG", "CD1", "HD1", "CE1", "HE1", "CZ", "HZ", "CE2", "HE2", "CD2", "HD2", "C", "O", "OXT"],
                        "PRO": ["N", "CD", "HD2", "HD3", "CG", "HG2", "HG3", "CB", "HB2", "HB3", "CA", "HA", "C", "O", "OXT"],
                        "SER": ["N", "H", "CA", "HA", "CB", "HB2", "HB3", "OG", "HG", "C", "O", "OXT"],
                        "THR": ["N", "H", "CA", "HA", "CB", "HB", "CG2", "HG21", "HG22", "HG23", "OG1", "HG1", "C", "O", "OXT"],
                        "TRP": ["N", "H", "CA", "HA", "CB", "HB2", "HB3", "CG", "CD1", "HD1", "NE1", "HE1", "CE2", "CZ2", "HZ2", "CH2", "HH2", "CZ3", "HZ3", "CE3", "HE3", "CD2", "C", "O", "OXT"],
                        "TYR": ["N", "H", "CA", "HA", "CB", "HB2", "HB3", "CG", "CD1", "HD1", "CE1", "HE1", "CZ", "OH", "HH", "CE2", "HE2", "CD2", "HD2", "C", "O", "OXT"],
                        "VAL": ["N", "H", "CA", "HA", "CB", "HB", "CG1", "HG11", "HG12", "HG13", "CG2", "HG21", "HG22", "HG23", "C", "O", "OXT"],
                        "NHE": ["N", "HN1", "HN2"],
                        "NME": ["N", "H", "CH3", "HH31", "HH32", "HH33"]
}
"""dict() that lists the atoms in the C-terminal version of a residue. (key, value) pairs are
(3-letter AA name, list of atom names) where the list of atom names are the modified list of 
atom names for the C-terminal version of that residue."""

RESIDUE_NTERMINAL_ATOM_LIST: Dict[str, List[str]] = {
                        'ACE': {'H1': ['CH3'], 'CH3': ['H1', 'H2', 'H3', 'C'], 'H2': ['CH3'], 'H3': ['CH3'], 'C': ['CH3', 'O'], 'O': ['C']},
                        'ALA': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB1', 'HB2', 'HB3'], 'HB1': ['CB'], 'HB2': ['CB'], 'HB3': ['CB'], 'C': ['CA', 'O', '+1N'], 'O': ['C']},
                        'ARG': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'HG2', 'HG3', 'CD'], 'HG2': ['CG'], 'HG3': ['CG'], 'CD': ['CG', 'HD2', 'HD3', 'NE'], 'HD2': ['CD'], 'HD3': ['CD'], 'NE': ['CD', 'HE', 'CZ'], 'HE': ['NE'], 'CZ': ['NE', 'NH1', 'NH2'], 'NH1': ['CZ', 'HH11', 'HH12'], 'HH11': ['NH1'], 'HH12': ['NH1'], 'NH2': ['CZ', 'HH21', 'HH22'], 'HH21': ['NH2'], 'HH22': ['NH2'], 'C': ['CA', 'O', '+1N'], 'O': ['C']},
                        'ASN': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'OD1', 'ND2'], 'OD1': ['CG'], 'ND2': ['CG', 'HD21', 'HD22'], 'HD21': ['ND2'], 'HD22': ['ND2'], 'C': ['CA', 'O', '+1N'], 'O': ['C']},
                        'ASP': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'OD1', 'OD2'], 'OD1': ['CG'], 'OD2': ['CG'], 'C': ['CA', 'O', '+1N'], 'O': ['C']},
                        'CYS': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'SG'], 'HB2': ['CB'], 'HB3': ['CB'], 'SG': ['CB', 'HG'], 'HG': ['SG'], 'C': ['CA', 'O', '+1N'], 'O': ['C']},
                        'CYX': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'SG'], 'HB2': ['CB'], 'HB3': ['CB'], 'SG': ['CB'], 'C': ['CA', 'O', '+1N'], 'O': ['C']},
                        'GLN': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'HG2', 'HG3', 'CD'], 'HG2': ['CG'], 'HG3': ['CG'], 'CD': ['CG', 'OE1', 'NE2'], 'OE1': ['CD'], 'NE2': ['CD', 'HE21', 'HE22'], 'HE21': ['NE2'], 'HE22': ['NE2'], 'C': ['CA', 'O', '+1N'], 'O': ['C']},
                        'GLU': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'HG2', 'HG3', 'CD'], 'HG2': ['CG'], 'HG3': ['CG'], 'CD': ['CG', 'OE1', 'OE2'], 'OE1': ['CD'], 'OE2': ['CD'], 'C': ['CA', 'O', '+1N'], 'O': ['C']},
                        'GLY': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA2', 'HA3', 'C'], 'HA2': ['CA'], 'HA3': ['CA'], 'C': ['CA', 'O', '+1N'], 'O': ['C']},
                        'HID': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'ND1', 'CD2'], 'ND1': ['CG', 'HD1', 'CE1'], 'HD1': ['ND1'], 'CE1': ['ND1', 'HE1', 'NE2'], 'HE1': ['CE1'], 'NE2': ['CE1', 'CD2'], 'CD2': ['CG', 'NE2', 'HD2'], 'HD2': ['CD2'], 'C': ['CA', 'O', '+1N'], 'O': ['C']},
                        'HIE': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'ND1', 'CD2'], 'ND1': ['CG', 'CE1'], 'CE1': ['ND1', 'HE1', 'NE2'], 'HE1': ['CE1'], 'NE2': ['CE1', 'HE2', 'CD2'], 'HE2': ['NE2'], 'CD2': ['CG', 'NE2', 'HD2'], 'HD2': ['CD2'], 'C': ['CA', 'O', '+1N'], 'O': ['C']},
                        'HIP': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'ND1', 'CD2'], 'ND1': ['CG', 'HD1', 'CE1'], 'HD1': ['ND1'], 'CE1': ['ND1', 'HE1', 'NE2'], 'HE1': ['CE1'], 'NE2': ['CE1', 'HE2', 'CD2'], 'HE2': ['NE2'], 'CD2': ['CG', 'NE2', 'HD2'], 'HD2': ['CD2'], 'C': ['CA', 'O', '+1N'], 'O': ['C']},
                        'ILE': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB', 'CG2', 'CG1'], 'HB': ['CB'], 'CG2': ['CB', 'HG21', 'HG22', 'HG23'], 'HG21': ['CG2'], 'HG22': ['CG2'], 'HG23': ['CG2'], 'CG1': ['CB', 'HG12', 'HG13', 'CD1'], 'HG12': ['CG1'], 'HG13': ['CG1'], 'CD1': ['CG1', 'HD11', 'HD12', 'HD13'], 'HD11': ['CD1'], 'HD12': ['CD1'], 'HD13': ['CD1'], 'C': ['CA', 'O', '+1N'], 'O': ['C']},
                        'LEU': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'HG', 'CD1', 'CD2'], 'HG': ['CG'], 'CD1': ['CG', 'HD11', 'HD12', 'HD13'], 'HD11': ['CD1'], 'HD12': ['CD1'], 'HD13': ['CD1'], 'CD2': ['CG', 'HD21', 'HD22', 'HD23'], 'HD21': ['CD2'], 'HD22': ['CD2'], 'HD23': ['CD2'], 'C': ['CA', 'O', '+1N'], 'O': ['C']},
                        'LYS': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'HG2', 'HG3', 'CD'], 'HG2': ['CG'], 'HG3': ['CG'], 'CD': ['CG', 'HD2', 'HD3', 'CE'], 'HD2': ['CD'], 'HD3': ['CD'], 'CE': ['CD', 'HE2', 'HE3', 'NZ'], 'HE2': ['CE'], 'HE3': ['CE'], 'NZ': ['CE', 'HZ1', 'HZ2', 'HZ3'], 'HZ1': ['NZ'], 'HZ2': ['NZ'], 'HZ3': ['NZ'], 'C': ['CA', 'O', '+1N'], 'O': ['C']},
                        'MET': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'HG2', 'HG3', 'SD'], 'HG2': ['CG'], 'HG3': ['CG'], 'SD': ['CG', 'CE'], 'CE': ['SD', 'HE1', 'HE2', 'HE3'], 'HE1': ['CE'], 'HE2': ['CE'], 'HE3': ['CE'], 'C': ['CA', 'O', '+1N'], 'O': ['C']},
                        'PHE': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'CD1', 'CD2'], 'CD1': ['CG', 'HD1', 'CE1'], 'HD1': ['CD1'], 'CE1': ['CD1', 'HE1', 'CZ'], 'HE1': ['CE1'], 'CZ': ['CE1', 'HZ', 'CE2'], 'HZ': ['CZ'], 'CE2': ['CZ', 'HE2', 'CD2'], 'HE2': ['CE2'], 'CD2': ['CG', 'CE2', 'HD2'], 'HD2': ['CD2'], 'C': ['CA', 'O', '+1N'], 'O': ['C']},
                        'PRO': {'N': ['H2', 'H3', 'CD', 'CA'], 'H2': ['N'], 'H3': ['N'], 'CD': ['N', 'HD2', 'HD3', 'CG'], 'HD2': ['CD'], 'HD3': ['CD'], 'CG': ['CD', 'HG2', 'HG3', 'CB'], 'HG2': ['CG'], 'HG3': ['CG'], 'CB': ['CG', 'HB2', 'HB3', 'CA'], 'HB2': ['CB'], 'HB3': ['CB'], 'CA': ['N', 'CB', 'HA', 'C'], 'HA': ['CA'], 'C': ['CA', 'O', '+1N'], 'O': ['C']},
                        'SER': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'OG'], 'HB2': ['CB'], 'HB3': ['CB'], 'OG': ['CB', 'HG'], 'HG': ['OG'], 'C': ['CA', 'O', '+1N'], 'O': ['C']},
                        'THR': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB', 'CG2', 'OG1'], 'HB': ['CB'], 'CG2': ['CB', 'HG21', 'HG22', 'HG23'], 'HG21': ['CG2'], 'HG22': ['CG2'], 'HG23': ['CG2'], 'OG1': ['CB', 'HG1'], 'HG1': ['OG1'], 'C': ['CA', 'O', '+1N'], 'O': ['C']},
                        'TRP': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'CD1', 'CD2'], 'CD1': ['CG', 'HD1', 'NE1'], 'HD1': ['CD1'], 'NE1': ['CD1', 'HE1', 'CE2'], 'HE1': ['NE1'], 'CE2': ['NE1', 'CZ2', 'CD2'], 'CZ2': ['CE2', 'HZ2', 'CH2'], 'HZ2': ['CZ2'], 'CH2': ['CZ2', 'HH2', 'CZ3'], 'HH2': ['CH2'], 'CZ3': ['CH2', 'HZ3', 'CE3'], 'HZ3': ['CZ3'], 'CE3': ['CZ3', 'HE3', 'CD2'], 'HE3': ['CE3'], 'CD2': ['CG', 'CE2', 'CE3'], 'C': ['CA', 'O', '+1N'], 'O': ['C']},
                        'TYR': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB2', 'HB3', 'CG'], 'HB2': ['CB'], 'HB3': ['CB'], 'CG': ['CB', 'CD1', 'CD2'], 'CD1': ['CG', 'HD1', 'CE1'], 'HD1': ['CD1'], 'CE1': ['CD1', 'HE1', 'CZ'], 'HE1': ['CE1'], 'CZ': ['CE1', 'OH', 'CE2'], 'OH': ['CZ', 'HH'], 'HH': ['OH'], 'CE2': ['CZ', 'HE2', 'CD2'], 'HE2': ['CE2'], 'CD2': ['CG', 'CE2', 'HD2'], 'HD2': ['CD2'], 'C': ['CA', 'O', '+1N'], 'O': ['C']},
                        'VAL': {'N': ['H1', 'H2', 'H3', 'CA'], 'H1': ['N'], 'H2': ['N'], 'H3': ['N'], 'CA': ['N', 'HA', 'CB', 'C'], 'HA': ['CA'], 'CB': ['CA', 'HB', 'CG1', 'CG2'], 'HB': ['CB'], 'CG1': ['CB', 'HG11', 'HG12', 'HG13'], 'HG11': ['CG1'], 'HG12': ['CG1'], 'HG13': ['CG1'], 'CG2': ['CB', 'HG21', 'HG22', 'HG23'], 'HG21': ['CG2'], 'HG22': ['CG2'], 'HG23': ['CG2'], 'C': ['CA', 'O', '+1N'], 'O': ['C']}
}
"""dict() that lists the atoms in the N-terminal version of a residue. (key, value) pairs are
(3-letter AA name, list of atom names) where the list of atom names are the modified list of 
atom names for the N-terminal version of that residue."""

RESIDUE_CONNECTIVITY_MAP_NTERMINAL: Dict[str, Dict[str, List[str]]] = {
                        "ACE": {"H1": ["CH3"], "CH3": ["H1", "H2", "H3", "C"], "H2": ["CH3"], "H3": ["CH3"], "C": ["CH3", "O"], "O": ["C"]},
                        "ALA": {"N": ["H1", "H2", "H3", "CA"], "H1": ["N"], "H2": ["N"], "H3": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB1", "HB2", "HB3"], "HB1": ["CB"], "HB2": ["CB"], "HB3": ["CB"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                        "ARG": {"N": ["H1", "H2", "H3", "CA"], "H1": ["N"], "H2": ["N"], "H3": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "HG2", "HG3", "CD"], "HG2": ["CG"], "HG3": ["CG"], "CD": ["CG", "HD2", "HD3", "NE"], "HD2": ["CD"], "HD3": ["CD"], "NE": ["CD", "HE", "CZ"], "HE": ["NE"], "CZ": ["NE", "NH1", "NH2"], "NH1": ["CZ", "HH11", "HH12"], "HH11": ["NH1"], "HH12": ["NH1"], "NH2": ["CZ", "HH21", "HH22"], "HH21": ["NH2"], "HH22": ["NH2"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                        "ASN": {"N": ["H1", "H2", "H3", "CA"], "H1": ["N"], "H2": ["N"], "H3": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "OD1", "ND2"], "OD1": ["CG"], "ND2": ["CG", "HD21", "HD22"], "HD21": ["ND2"], "HD22": ["ND2"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                        "ASP": {"N": ["H1", "H2", "H3", "CA"], "H1": ["N"], "H2": ["N"], "H3": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "OD1", "OD2"], "OD1": ["CG"], "OD2": ["CG"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                        "CYS": {"N": ["H1", "H2", "H3", "CA"], "H1": ["N"], "H2": ["N"], "H3": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "SG"], "HB2": ["CB"], "HB3": ["CB"], "SG": ["CB", "HG"], "HG": ["SG"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                        "CYX": {"N": ["H1", "H2", "H3", "CA"], "H1": ["N"], "H2": ["N"], "H3": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "SG"], "HB2": ["CB"], "HB3": ["CB"], "SG": ["CB"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                        "GLN": {"N": ["H1", "H2", "H3", "CA"], "H1": ["N"], "H2": ["N"], "H3": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "HG2", "HG3", "CD"], "HG2": ["CG"], "HG3": ["CG"], "CD": ["CG", "OE1", "NE2"], "OE1": ["CD"], "NE2": ["CD", "HE21", "HE22"], "HE21": ["NE2"], "HE22": ["NE2"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                        "GLU": {"N": ["H1", "H2", "H3", "CA"], "H1": ["N"], "H2": ["N"], "H3": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "HG2", "HG3", "CD"], "HG2": ["CG"], "HG3": ["CG"], "CD": ["CG", "OE1", "OE2"], "OE1": ["CD"], "OE2": ["CD"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                        "GLY": {"N": ["H1", "H2", "H3", "CA"], "H1": ["N"], "H2": ["N"], "H3": ["N"], "CA": ["N", "HA2", "HA3", "C"], "HA2": ["CA"], "HA3": ["CA"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                        "HID": {"N": ["H1", "H2", "H3", "CA"], "H1": ["N"], "H2": ["N"], "H3": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "ND1", "CD2"], "ND1": ["CG", "HD1", "CE1"], "HD1": ["ND1"], "CE1": ["ND1", "HE1", "NE2"], "HE1": ["CE1"], "NE2": ["CE1", "CD2"], "CD2": ["CG", "NE2", "HD2"], "HD2": ["CD2"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                        "HIE": {"N": ["H1", "H2", "H3", "CA"], "H1": ["N"], "H2": ["N"], "H3": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "ND1", "CD2"], "ND1": ["CG", "CE1"], "CE1": ["ND1", "HE1", "NE2"], "HE1": ["CE1"], "NE2": ["CE1", "HE2", "CD2"], "HE2": ["NE2"], "CD2": ["CG", "NE2", "HD2"], "HD2": ["CD2"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                        "HIP": {"N": ["H1", "H2", "H3", "CA"], "H1": ["N"], "H2": ["N"], "H3": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "ND1", "CD2"], "ND1": ["CG", "HD1", "CE1"], "HD1": ["ND1"], "CE1": ["ND1", "HE1", "NE2"], "HE1": ["CE1"], "NE2": ["CE1", "HE2", "CD2"], "HE2": ["NE2"], "CD2": ["CG", "NE2", "HD2"], "HD2": ["CD2"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                        "ILE": {"N": ["H1", "H2", "H3", "CA"], "H1": ["N"], "H2": ["N"], "H3": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB", "CG2", "CG1"], "HB": ["CB"], "CG2": ["CB", "HG21", "HG22", "HG23"], "HG21": ["CG2"], "HG22": ["CG2"], "HG23": ["CG2"], "CG1": ["CB", "HG12", "HG13", "CD1"], "HG12": ["CG1"], "HG13": ["CG1"], "CD1": ["CG1", "HD11", "HD12", "HD13"], "HD11": ["CD1"], "HD12": ["CD1"], "HD13": ["CD1"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                        "LEU": {"N": ["H1", "H2", "H3", "CA"], "H1": ["N"], "H2": ["N"], "H3": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "HG", "CD1", "CD2"], "HG": ["CG"], "CD1": ["CG", "HD11", "HD12", "HD13"], "HD11": ["CD1"], "HD12": ["CD1"], "HD13": ["CD1"], "CD2": ["CG", "HD21", "HD22", "HD23"], "HD21": ["CD2"], "HD22": ["CD2"], "HD23": ["CD2"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                        "LYS": {"N": ["H1", "H2", "H3", "CA"], "H1": ["N"], "H2": ["N"], "H3": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "HG2", "HG3", "CD"], "HG2": ["CG"], "HG3": ["CG"], "CD": ["CG", "HD2", "HD3", "CE"], "HD2": ["CD"], "HD3": ["CD"], "CE": ["CD", "HE2", "HE3", "NZ"], "HE2": ["CE"], "HE3": ["CE"], "NZ": ["CE", "HZ1", "HZ2", "HZ3"], "HZ1": ["NZ"], "HZ2": ["NZ"], "HZ3": ["NZ"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                        "MET": {"N": ["H1", "H2", "H3", "CA"], "H1": ["N"], "H2": ["N"], "H3": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "HG2", "HG3", "SD"], "HG2": ["CG"], "HG3": ["CG"], "SD": ["CG", "CE"], "CE": ["SD", "HE1", "HE2", "HE3"], "HE1": ["CE"], "HE2": ["CE"], "HE3": ["CE"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                        "PHE": {"N": ["H1", "H2", "H3", "CA"], "H1": ["N"], "H2": ["N"], "H3": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "CD1", "CD2"], "CD1": ["CG", "HD1", "CE1"], "HD1": ["CD1"], "CE1": ["CD1", "HE1", "CZ"], "HE1": ["CE1"], "CZ": ["CE1", "HZ", "CE2"], "HZ": ["CZ"], "CE2": ["CZ", "HE2", "CD2"], "HE2": ["CE2"], "CD2": ["CG", "CE2", "HD2"], "HD2": ["CD2"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                        "PRO": {"N": ["H2", "H3", "CD", "CA"], "H2": ["N"], "H3": ["N"], "CD": ["N", "HD2", "HD3", "CG"], "HD2": ["CD"], "HD3": ["CD"], "CG": ["CD", "HG2", "HG3", "CB"], "HG2": ["CG"], "HG3": ["CG"], "CB": ["CG", "HB2", "HB3", "CA"], "HB2": ["CB"], "HB3": ["CB"], "CA": ["N", "CB", "HA", "C"], "HA": ["CA"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                        "SER": {"N": ["H1", "H2", "H3", "CA"], "H1": ["N"], "H2": ["N"], "H3": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "OG"], "HB2": ["CB"], "HB3": ["CB"], "OG": ["CB", "HG"], "HG": ["OG"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                        "THR": {"N": ["H1", "H2", "H3", "CA"], "H1": ["N"], "H2": ["N"], "H3": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB", "CG2", "OG1"], "HB": ["CB"], "CG2": ["CB", "HG21", "HG22", "HG23"], "HG21": ["CG2"], "HG22": ["CG2"], "HG23": ["CG2"], "OG1": ["CB", "HG1"], "HG1": ["OG1"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                        "TRP": {"N": ["H1", "H2", "H3", "CA"], "H1": ["N"], "H2": ["N"], "H3": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "CD1", "CD2"], "CD1": ["CG", "HD1", "NE1"], "HD1": ["CD1"], "NE1": ["CD1", "HE1", "CE2"], "HE1": ["NE1"], "CE2": ["NE1", "CZ2", "CD2"], "CZ2": ["CE2", "HZ2", "CH2"], "HZ2": ["CZ2"], "CH2": ["CZ2", "HH2", "CZ3"], "HH2": ["CH2"], "CZ3": ["CH2", "HZ3", "CE3"], "HZ3": ["CZ3"], "CE3": ["CZ3", "HE3", "CD2"], "HE3": ["CE3"], "CD2": ["CG", "CE2", "CE3"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                        "TYR": {"N": ["H1", "H2", "H3", "CA"], "H1": ["N"], "H2": ["N"], "H3": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB2", "HB3", "CG"], "HB2": ["CB"], "HB3": ["CB"], "CG": ["CB", "CD1", "CD2"], "CD1": ["CG", "HD1", "CE1"], "HD1": ["CD1"], "CE1": ["CD1", "HE1", "CZ"], "HE1": ["CE1"], "CZ": ["CE1", "OH", "CE2"], "OH": ["CZ", "HH"], "HH": ["OH"], "CE2": ["CZ", "HE2", "CD2"], "HE2": ["CE2"], "CD2": ["CG", "CE2", "HD2"], "HD2": ["CD2"], "C": ["CA", "O", "+1N"], "O": ["C"]},
                        "VAL": {"N": ["H1", "H2", "H3", "CA"], "H1": ["N"], "H2": ["N"], "H3": ["N"], "CA": ["N", "HA", "CB", "C"], "HA": ["CA"], "CB": ["CA", "HB", "CG1", "CG2"], "HB": ["CB"], "CG1": ["CB", "HG11", "HG12", "HG13"], "HG11": ["CG1"], "HG12": ["CG1"], "HG13": ["CG1"], "CG2": ["CB", "HG21", "HG22", "HG23"], "HG21": ["CG2"], "HG22": ["CG2"], "HG23": ["CG2"], "C": ["CA", "O", "+1N"], "O": ["C"]}
}
"""dict() that maps the connectivity of atom's based on their parent residue and atom identity.
(key, value) pairs are (3-letter AA name, connector), where connector is another dict() with 
(key, value) pairs of (atom name, list of connected atoms). Similar to RESIDUE_CONNECTIVITY_MAP
except has the mappings for the N-terminal version of each residue."""

RESIDUE_CATEGORIES: Dict[str, List[str]] = {
        "charged": ["R","H","K","D","E"],
        "negative": ["D","E"],
        "neutral": ["S","T","N","Q","C","Y","A","V","I","L","P","M","F","W","G"],
        "nonpolar": ["A","V","I","L","P","M","F","W","G"],
        "polar": ["R","H","K","D","E","S","T","N","Q","C","Y"],
        "positive": ["R","H","K"],
        "polar_neutral": ["S","T","N","Q","C","Y"],
        "strong_h_bond_donor": ["R","H","K","Y","C"],
        "weak_h_bond_donor": ["S","T","N","Q","W"],
}
"""dict() that describes basic characteristics of amino acids. Has (key,value) pairs
of ('characteric', list() of one-letter amino-acid codes). Covered characteristics are:
polar, nonpolar, charged, positive, negative, neutral, polar_neutral, strong_h_bond_donor,
weak_h_bond_donor."""

RESIDUE_VOLUME_MAPPER: Dict[str, float] = {
        "A": 88.6,
        "C": 108.5,
        "D": 111.1,
        "E": 138.4,
        "F": 189.9,
        "G": 60.1,
        "H": 153.2,
        "I": 166.7,
        "K": 168.6,
        "L": 166.7,
        "M": 162.9,
        "N": 114.1,
        "P": 112.7,
        "Q": 143.8,
        "R": 173.4,
        "S": 89.0,
        "T": 116.1,
        "V": 140.0,
        "W": 227.8,
        "Y": 193.6
}
"""dict() that maps one-letter amino-acid codes to their volume in cubic angstroms. 
source: https://www.imgt.org/IMGTeducation/Aide-memoire/_UK/aminoacids/abbreviation.html"""

CAA_CHARGE_MAPPER: Dict[str, int] = {
        "ALA": 0,
        "CYS": 0,
        "ASP": -1,
        "ASH": 0,
        "GLU": -1,
        "PHE": 0,
        "GLY": 0,
        "ILE": 0,
        "LYS": 1,
        "LEU": 0,
        "MET": 0,
        "ASN": 0,
        "PRO": 0,
        "GLN": 0,
        "ARG": 1,
        "SER": 0,
        "THR": 0,
        "TYR": 0,
        "VAL": 0,
        "TRP": 0,
        "HID": 0,
        "HIE": 0,
        "HIP": 1,
}
"""dict() that maps three-letter canonical amino-acid codes to their formal charge. 
Note that HIS is temporarily removed from the map due to its potential 3 titration state.
This is used as the pool for target mutation selection when charge related keyword for mutation
is used"""

AA_CHARGE_MAPPER: Dict[str, int] = {
        "ALA": 0,
        "CYS": 0,
        "ASP": -1,
        "GLU": -1,
        "PHE": 0,
        "GLY": 0,
        "ILE": 0,
        "LYS": 1,
        "LEU": 0,
        "MET": 0,
        "ASN": 0,
        "PRO": 0,
        "GLN": 0,
        "ARG": 1,
        "SER": 0,
        "THR": 0,
        "VAL": 0,
        "TRP": 0,
        "TYR": 0,
        "HIS": 0,
        "HIE": 0,
        "HID": 0,
        "HIP": 1,
}
"""dict() that maps three-letter amino-acid codes to their formal charge. not limited to CAA.
This map includes residues of different titration states. This is used in determine the charge
of the original residue when charge related keyword for mutation is used"""

RESIDUE_CHARGE_MAP = {
    "ff19sb" : {
        'HOH': {
            'O' :0.0, #TODO(CJ)            
            'H1':0.0, #TODO(CJ)            
            'H2':0.0 #TODO(CJ)            
        },
        'ALA': {
            'N': -0.4157,
            'H': 0.2719,
            'CA': 0.0337,
            'HA': 0.0823,
            'CB': -0.1825,
            'HB1': 0.0603,
            'HB2': 0.0603,
            'HB3': 0.0603,
            'C': 0.5973,
            'O': -0.5679
        },
        'ARG': {
            'N': -0.3479,
            'H': 0.2747,
            'CA': -0.2637,
            'HA': 0.156,
            'CB': -0.0007,
            'HB2': 0.0327,
            'HB3': 0.0327,
            'CG': 0.039,
            'HG2': 0.0285,
            'HG3': 0.0285,
            'CD': 0.0486,
            'HD2': 0.0687,
            'HD3': 0.0687,
            'NE': -0.5295,
            'HE': 0.3456,
            'CZ': 0.8076,
            'NH1': -0.8627,
            'HH11': 0.4478,
            'HH12': 0.4478,
            'NH2': -0.8627,
            'HH21': 0.4478,
            'HH22': 0.4478,
            'C': 0.7341,
            'O': -0.5894
        },
        'ASH': {
            'N': -0.4157,
            'H': 0.2719,
            'CA': 0.0341,
            'HA': 0.0864,
            'CB': -0.0316,
            'HB2': 0.0488,
            'HB3': 0.0488,
            'CG': 0.6462,
            'OD1': -0.5554,
            'OD2': -0.6376,
            'HD2': 0.4747,
            'C': 0.5973,
            'O': -0.5679
        },
        'ASN': {
            'N': -0.4157,
            'H': 0.2719,
            'CA': 0.0143,
            'HA': 0.1048,
            'CB': -0.2041,
            'HB2': 0.0797,
            'HB3': 0.0797,
            'CG': 0.713,
            'OD1': -0.5931,
            'ND2': -0.9191,
            'HD21': 0.4196,
            'HD22': 0.4196,
            'C': 0.5973,
            'O': -0.5679
        },
        'ASP': {
            'N': -0.5163,
            'H': 0.2936,
            'CA': 0.0381,
            'HA': 0.088,
            'CB': -0.0303,
            'HB2': -0.0122,
            'HB3': -0.0122,
            'CG': 0.7994,
            'OD1': -0.8014,
            'OD2': -0.8014,
            'C': 0.5366,
            'O': -0.5819
        },
        'CYM': {
            'N': -0.4157,
            'H': 0.2719,
            'CA': -0.0351,
            'HA': 0.0508,
            'CB': -0.2413,
            'HB3': 0.1122,
            'HB2': 0.1122,
            'SG': -0.8844,
            'C': 0.5973,
            'O': -0.5679
        },
        'CYS': {
            'N': -0.4157,
            'H': 0.2719,
            'CA': 0.0213,
            'HA': 0.1124,
            'CB': -0.1231,
            'HB2': 0.1112,
            'HB3': 0.1112,
            'SG': -0.3119,
            'HG': 0.1933,
            'C': 0.5973,
            'O': -0.5679
        },
        'CYX': {
            'N': -0.4157,
            'H': 0.2719,
            'CA': 0.0429,
            'HA': 0.0766,
            'CB': -0.079,
            'HB2': 0.091,
            'HB3': 0.091,
            'SG': -0.1081,
            'C': 0.5973,
            'O': -0.5679
        },
        'GLH': {
            'N': -0.4157,
            'H': 0.2719,
            'CA': 0.0145,
            'HA': 0.0779,
            'CB': -0.0071,
            'HB2': 0.0256,
            'HB3': 0.0256,
            'CG': -0.0174,
            'HG2': 0.043,
            'HG3': 0.043,
            'CD': 0.6801,
            'OE1': -0.5838,
            'OE2': -0.6511,
            'HE2': 0.4641,
            'C': 0.5973,
            'O': -0.5679
        },
        'GLN': {
            'N': -0.4157,
            'H': 0.2719,
            'CA': -0.0031,
            'HA': 0.085,
            'CB': -0.0036,
            'HB2': 0.0171,
            'HB3': 0.0171,
            'CG': -0.0645,
            'HG2': 0.0352,
            'HG3': 0.0352,
            'CD': 0.6951,
            'OE1': -0.6086,
            'NE2': -0.9407,
            'HE21': 0.4251,
            'HE22': 0.4251,
            'C': 0.5973,
            'O': -0.5679
        },
        'GLU': {
            'N': -0.5163,
            'H': 0.2936,
            'CA': 0.0397,
            'HA': 0.1105,
            'CB': 0.056,
            'HB2': -0.0173,
            'HB3': -0.0173,
            'CG': 0.0136,
            'HG2': -0.0425,
            'HG3': -0.0425,
            'CD': 0.8054,
            'OE1': -0.8188,
            'OE2': -0.8188,
            'C': 0.5366,
            'O': -0.5819
        },
        'GLY': {
            'N': -0.4157,
            'H': 0.2719,
            'CA': -0.0252,
            'HA2': 0.0698,
            'HA3': 0.0698,
            'C': 0.5973,
            'O': -0.5679
        },
        'HID': {
            'N': -0.4157,
            'H': 0.2719,
            'CA': 0.0188,
            'HA': 0.0881,
            'CB': -0.0462,
            'HB2': 0.0402,
            'HB3': 0.0402,
            'CG': -0.0266,
            'ND1': -0.3811,
            'HD1': 0.3649,
            'CE1': 0.2057,
            'HE1': 0.1392,
            'NE2': -0.5727,
            'CD2': 0.1292,
            'HD2': 0.1147,
            'C': 0.5973,
            'O': -0.5679
        },
        'HIE': {
            'N': -0.4157,
            'H': 0.2719,
            'CA': -0.0581,
            'HA': 0.136,
            'CB': -0.0074,
            'HB2': 0.0367,
            'HB3': 0.0367,
            'CG': 0.1868,
            'ND1': -0.5432,
            'CE1': 0.1635,
            'HE1': 0.1435,
            'NE2': -0.2795,
            'HE2': 0.3339,
            'CD2': -0.2207,
            'HD2': 0.1862,
            'C': 0.5973,
            'O': -0.5679
        },
        'HIP': {
            'N': -0.3479,
            'H': 0.2747,
            'CA': -0.1354,
            'HA': 0.1212,
            'CB': -0.0414,
            'HB2': 0.081,
            'HB3': 0.081,
            'CG': -0.0012,
            'ND1': -0.1513,
            'HD1': 0.3866,
            'CE1': -0.017,
            'HE1': 0.2681,
            'NE2': -0.1718,
            'HE2': 0.3911,
            'CD2': -0.1141,
            'HD2': 0.2317,
            'C': 0.7341,
            'O': -0.5894
        },
        'HYP': {
            'N': -0.2548,
            'CD': 0.0595,
            'HD22': 0.07,
            'HD23': 0.07,
            'CG': 0.04,
            'HG': 0.0416,
            'OD1': -0.6134,
            'HD1': 0.3851,
            'CB': 0.0203,
            'HB2': 0.0426,
            'HB3': 0.0426,
            'CA': 0.0047,
            'HA': 0.077,
            'C': 0.5896,
            'O': -0.5748
        },
        'ILE': {
            'N': -0.4157,
            'H': 0.2719,
            'CA': -0.0597,
            'HA': 0.0869,
            'CB': 0.1303,
            'HB': 0.0187,
            'CG2': -0.3204,
            'HG21': 0.0882,
            'HG22': 0.0882,
            'HG23': 0.0882,
            'CG1': -0.043,
            'HG12': 0.0236,
            'HG13': 0.0236,
            'CD1': -0.066,
            'HD11': 0.0186,
            'HD12': 0.0186,
            'HD13': 0.0186,
            'C': 0.5973,
            'O': -0.5679
        },
        'LEU': {
            'N': -0.4157,
            'H': 0.2719,
            'CA': -0.0518,
            'HA': 0.0922,
            'CB': -0.1102,
            'HB2': 0.0457,
            'HB3': 0.0457,
            'CG': 0.3531,
            'HG': -0.0361,
            'CD1': -0.4121,
            'HD11': 0.1,
            'HD12': 0.1,
            'HD13': 0.1,
            'CD2': -0.4121,
            'HD21': 0.1,
            'HD22': 0.1,
            'HD23': 0.1,
            'C': 0.5973,
            'O': -0.5679
        },
        'LYN': {
            'N': -0.4157,
            'H': 0.2719,
            'CA': -0.07206,
            'HA': 0.0994,
            'CB': -0.04845,
            'HB2': 0.034,
            'HB3': 0.034,
            'CG': 0.06612,
            'HG2': 0.01041,
            'HG3': 0.01041,
            'CD': -0.03768,
            'HD2': 0.01155,
            'HD3': 0.01155,
            'CE': 0.32604,
            'HE2': -0.03358,
            'HE3': -0.03358,
            'NZ': -1.03581,
            'HZ2': 0.38604,
            'HZ3': 0.38604,
            'C': 0.5973,
            'O': -0.5679
        },
        'LYS': {
            'N': -0.3479,
            'H': 0.2747,
            'CA': -0.24,
            'HA': 0.1426,
            'CB': -0.0094,
            'HB2': 0.0362,
            'HB3': 0.0362,
            'CG': 0.0187,
            'HG2': 0.0103,
            'HG3': 0.0103,
            'CD': -0.0479,
            'HD2': 0.0621,
            'HD3': 0.0621,
            'CE': -0.0143,
            'HE2': 0.1135,
            'HE3': 0.1135,
            'NZ': -0.3854,
            'HZ1': 0.34,
            'HZ2': 0.34,
            'HZ3': 0.34,
            'C': 0.7341,
            'O': -0.5894
        },
        'MET': {
            'N': -0.4157,
            'H': 0.2719,
            'CA': -0.0237,
            'HA': 0.088,
            'CB': 0.0342,
            'HB2': 0.0241,
            'HB3': 0.0241,
            'CG': 0.0018,
            'HG2': 0.044,
            'HG3': 0.044,
            'SD': -0.2737,
            'CE': -0.0536,
            'HE1': 0.0684,
            'HE2': 0.0684,
            'HE3': 0.0684,
            'C': 0.5973,
            'O': -0.5679
        },
        'PHE': {
            'N': -0.4157,
            'H': 0.2719,
            'CA': -0.0024,
            'HA': 0.0978,
            'CB': -0.0343,
            'HB2': 0.0295,
            'HB3': 0.0295,
            'CG': 0.0118,
            'CD1': -0.1256,
            'HD1': 0.133,
            'CE1': -0.1704,
            'HE1': 0.143,
            'CZ': -0.1072,
            'HZ': 0.1297,
            'CE2': -0.1704,
            'HE2': 0.143,
            'CD2': -0.1256,
            'HD2': 0.133,
            'C': 0.5973,
            'O': -0.5679
        },
        'PRO': {
            'N': -0.2548,
            'CD': 0.0192,
            'HD2': 0.0391,
            'HD3': 0.0391,
            'CG': 0.0189,
            'HG2': 0.0213,
            'HG3': 0.0213,
            'CB': -0.007,
            'HB2': 0.0253,
            'HB3': 0.0253,
            'CA': -0.0266,
            'HA': 0.0641,
            'C': 0.5896,
            'O': -0.5748
        },
        'SER': {
            'N': -0.4157,
            'H': 0.2719,
            'CA': -0.0249,
            'HA': 0.0843,
            'CB': 0.2117,
            'HB2': 0.0352,
            'HB3': 0.0352,
            'OG': -0.6546,
            'HG': 0.4275,
            'C': 0.5973,
            'O': -0.5679
        },
        'THR': {
            'N': -0.4157,
            'H': 0.2719,
            'CA': -0.0389,
            'HA': 0.1007,
            'CB': 0.3654,
            'HB': 0.0043,
            'CG2': -0.2438,
            'HG21': 0.0642,
            'HG22': 0.0642,
            'HG23': 0.0642,
            'OG1': -0.6761,
            'HG1': 0.4102,
            'C': 0.5973,
            'O': -0.5679
        },
        'TRP': {
            'N': -0.4157,
            'H': 0.2719,
            'CA': -0.0275,
            'HA': 0.1123,
            'CB': -0.005,
            'HB2': 0.0339,
            'HB3': 0.0339,
            'CG': -0.1415,
            'CD1': -0.1638,
            'HD1': 0.2062,
            'NE1': -0.3418,
            'HE1': 0.3412,
            'CE2': 0.138,
            'CZ2': -0.2601,
            'HZ2': 0.1572,
            'CH2': -0.1134,
            'HH2': 0.1417,
            'CZ3': -0.1972,
            'HZ3': 0.1447,
            'CE3': -0.2387,
            'HE3': 0.17,
            'CD2': 0.1243,
            'C': 0.5973,
            'O': -0.5679
        },
        'TYR': {
            'N': -0.4157,
            'H': 0.2719,
            'CA': -0.0014,
            'HA': 0.0876,
            'CB': -0.0152,
            'HB2': 0.0295,
            'HB3': 0.0295,
            'CG': -0.0011,
            'CD1': -0.1906,
            'HD1': 0.1699,
            'CE1': -0.2341,
            'HE1': 0.1656,
            'CZ': 0.3226,
            'OH': -0.5579,
            'HH': 0.3992,
            'CE2': -0.2341,
            'HE2': 0.1656,
            'CD2': -0.1906,
            'HD2': 0.1699,
            'C': 0.5973,
            'O': -0.5679
        },
        'VAL': {
            'N': -0.4157,
            'H': 0.2719,
            'CA': -0.0875,
            'HA': 0.0969,
            'CB': 0.2985,
            'HB': -0.0297,
            'CG1': -0.3192,
            'HG11': 0.0791,
            'HG12': 0.0791,
            'HG13': 0.0791,
            'CG2': -0.3192,
            'HG21': 0.0791,
            'HG22': 0.0791,
            'HG23': 0.0791,
            'C': 0.5973,
            'O': -0.5679
        },
    },
}
"""dict() that maps three-letter amino-acid codes to their atomic charge based on different
force fields (the 1st key). CAA and WAT This map includes residues of different titration states."""

RESIDUE_CHARGE_MAP_CTERMINAL = {
    "ff19sb" : {
        'ALA': {
            'N': -0.3821,
            'H': 0.2681,
            'CA': -0.1747,
            'HA': 0.1067,
            'CB': -0.2093,
            'HB1': 0.0764,
            'HB2': 0.0764,
            'HB3': 0.0764,
            'C': 0.7731,
            'O': -0.8055,
            'OXT': -0.8055
        },
        'ARG': {
            'N': -0.3481,
            'H': 0.2764,
            'CA': -0.3068,
            'HA': 0.1447,
            'CB': -0.0374,
            'HB2': 0.0371,
            'HB3': 0.0371,
            'CG': 0.0744,
            'HG2': 0.0185,
            'HG3': 0.0185,
            'CD': 0.1114,
            'HD2': 0.0468,
            'HD3': 0.0468,
            'NE': -0.5564,
            'HE': 0.3479,
            'CZ': 0.8368,
            'NH1': -0.8737,
            'HH11': 0.4493,
            'HH12': 0.4493,
            'NH2': -0.8737,
            'HH21': 0.4493,
            'HH22': 0.4493,
            'C': 0.8557,
            'O': -0.8266,
            'OXT': -0.8266
        },
        'ASN': {
            'N': -0.3821,
            'H': 0.2681,
            'CA': -0.208,
            'HA': 0.1358,
            'CB': -0.2299,
            'HB2': 0.1023,
            'HB3': 0.1023,
            'CG': 0.7153,
            'OD1': -0.601,
            'ND2': -0.9084,
            'HD21': 0.415,
            'HD22': 0.415,
            'C': 0.805,
            'O': -0.8147,
            'OXT': -0.8147
        },
        'ASP': {
            'N': -0.5192,
            'H': 0.3055,
            'CA': -0.1817,
            'HA': 0.1046,
            'CB': -0.0677,
            'HB2': -0.0212,
            'HB3': -0.0212,
            'CG': 0.8851,
            'OD1': -0.8162,
            'OD2': -0.8162,
            'C': 0.7256,
            'O': -0.7887,
            'OXT': -0.7887
        },
        'CYS': {
            'N': -0.3821,
            'H': 0.2681,
            'CA': -0.1635,
            'HA': 0.1396,
            'CB': -0.1996,
            'HB2': 0.1437,
            'HB3': 0.1437,
            'SG': -0.3102,
            'HG': 0.2068,
            'C': 0.7497,
            'O': -0.7981,
            'OXT': -0.7981
        },
        'CYX': {
            'N': -0.3821,
            'H': 0.2681,
            'CA': -0.1318,
            'HA': 0.0938,
            'CB': -0.1943,
            'HB2': 0.1228,
            'HB3': 0.1228,
            'SG': -0.0529,
            'C': 0.7618,
            'O': -0.8041,
            'OXT': -0.8041
        },
        'GLN': {
            'N': -0.3821,
            'H': 0.2681,
            'CA': -0.2248,
            'HA': 0.1232,
            'CB': -0.0664,
            'HB2': 0.0452,
            'HB3': 0.0452,
            'CG': -0.021,
            'HG2': 0.0203,
            'HG3': 0.0203,
            'CD': 0.7093,
            'OE1': -0.6098,
            'NE2': -0.9574,
            'HE21': 0.4304,
            'HE22': 0.4304,
            'C': 0.7775,
            'O': -0.8042,
            'OXT': -0.8042
        },
        'GLU': {
            'N': -0.5192,
            'H': 0.3055,
            'CA': -0.2059,
            'HA': 0.1399,
            'CB': 0.0071,
            'HB2': -0.0078,
            'HB3': -0.0078,
            'CG': 0.0675,
            'HG2': -0.0548,
            'HG3': -0.0548,
            'CD': 0.8183,
            'OE1': -0.822,
            'OE2': -0.822,
            'C': 0.742,
            'O': -0.793,
            'OXT': -0.793
        },
        'GLY': {
            'N': -0.3821,
            'H': 0.2681,
            'CA': -0.2493,
            'HA2': 0.1056,
            'HA3': 0.1056,
            'C': 0.7231,
            'O': -0.7855,
            'OXT': -0.7855
        },
        'HID': {
            'N': -0.3821,
            'H': 0.2681,
            'CA': -0.1739,
            'HA': 0.11,
            'CB': -0.1046,
            'HB2': 0.0565,
            'HB3': 0.0565,
            'CG': 0.0293,
            'ND1': -0.3892,
            'HD1': 0.3755,
            'CE1': 0.1925,
            'HE1': 0.1418,
            'NE2': -0.5629,
            'CD2': 0.1001,
            'HD2': 0.1241,
            'C': 0.7615,
            'O': -0.8016,
            'OXT': -0.8016
        },
        'HIE': {
            'N': -0.3821,
            'H': 0.2681,
            'CA': -0.2699,
            'HA': 0.165,
            'CB': -0.1068,
            'HB2': 0.062,
            'HB3': 0.062,
            'CG': 0.2724,
            'ND1': -0.5517,
            'CE1': 0.1558,
            'HE1': 0.1448,
            'NE2': -0.267,
            'HE2': 0.3319,
            'CD2': -0.2588,
            'HD2': 0.1957,
            'C': 0.7916,
            'O': -0.8065,
            'OXT': -0.8065
        },
        'HIP': {
            'N': -0.3481,
            'H': 0.2764,
            'CA': -0.1445,
            'HA': 0.1115,
            'CB': -0.08,
            'HB2': 0.0868,
            'HB3': 0.0868,
            'CG': 0.0298,
            'ND1': -0.1501,
            'HD1': 0.3883,
            'CE1': -0.0251,
            'HE1': 0.2694,
            'NE2': -0.1683,
            'HE2': 0.3913,
            'CD2': -0.1256,
            'HD2': 0.2336,
            'C': 0.8032,
            'O': -0.8177,
            'OXT': -0.8177
        },
        'HYP': {
            'N': -0.2802,
            'CD': 0.0778,
            'HD22': 0.0331,
            'HD23': 0.0331,
            'CG': 0.081,
            'HG': 0.0416,
            'OD1': -0.6134,
            'HD1': 0.3851,
            'CB': 0.0547,
            'HB2': 0.0426,
            'HB3': 0.0426,
            'CA': -0.0993,
            'HA': 0.0776,
            'C': 0.6631,
            'O': -0.7697,
            'OXT': -0.7697
        },
        'ILE': {
            'N': -0.3821,
            'H': 0.2681,
            'CA': -0.31,
            'HA': 0.1375,
            'CB': 0.0363,
            'HB': 0.0766,
            'CG2': -0.3498,
            'HG21': 0.1021,
            'HG22': 0.1021,
            'HG23': 0.1021,
            'CG1': -0.0323,
            'HG12': 0.0321,
            'HG13': 0.0321,
            'CD1': -0.0699,
            'HD11': 0.0196,
            'HD12': 0.0196,
            'HD13': 0.0196,
            'C': 0.8343,
            'O': -0.819,
            'OXT': -0.819
        },
        'LEU': {
            'N': -0.3821,
            'H': 0.2681,
            'CA': -0.2847,
            'HA': 0.1346,
            'CB': -0.2469,
            'HB2': 0.0974,
            'HB3': 0.0974,
            'CG': 0.3706,
            'HG': -0.0374,
            'CD1': -0.4163,
            'HD11': 0.1038,
            'HD12': 0.1038,
            'HD13': 0.1038,
            'CD2': -0.4163,
            'HD21': 0.1038,
            'HD22': 0.1038,
            'HD23': 0.1038,
            'C': 0.8326,
            'O': -0.8199,
            'OXT': -0.8199
        },
        'LYS': {
            'N': -0.3481,
            'H': 0.2764,
            'CA': -0.2903,
            'HA': 0.1438,
            'CB': -0.0538,
            'HB2': 0.0482,
            'HB3': 0.0482,
            'CG': 0.0227,
            'HG2': 0.0134,
            'HG3': 0.0134,
            'CD': -0.0392,
            'HD2': 0.0611,
            'HD3': 0.0611,
            'CE': -0.0176,
            'HE2': 0.1121,
            'HE3': 0.1121,
            'NZ': -0.3741,
            'HZ1': 0.3374,
            'HZ2': 0.3374,
            'HZ3': 0.3374,
            'C': 0.8488,
            'O': -0.8252,
            'OXT': -0.8252
        },
        'MET': {
            'N': -0.3821,
            'H': 0.2681,
            'CA': -0.2597,
            'HA': 0.1277,
            'CB': -0.0236,
            'HB2': 0.048,
            'HB3': 0.048,
            'CG': 0.0492,
            'HG2': 0.0317,
            'HG3': 0.0317,
            'SD': -0.2692,
            'CE': -0.0376,
            'HE1': 0.0625,
            'HE2': 0.0625,
            'HE3': 0.0625,
            'C': 0.8013,
            'O': -0.8105,
            'OXT': -0.8105
        },
        'PHE': {
            'N': -0.3821,
            'H': 0.2681,
            'CA': -0.1825,
            'HA': 0.1098,
            'CB': -0.0959,
            'HB2': 0.0443,
            'HB3': 0.0443,
            'CG': 0.0552,
            'CD1': -0.13,
            'HD1': 0.1408,
            'CE1': -0.1847,
            'HE1': 0.1461,
            'CZ': -0.0944,
            'HZ': 0.128,
            'CE2': -0.1847,
            'HE2': 0.1461,
            'CD2': -0.13,
            'HD2': 0.1408,
            'C': 0.766,
            'O': -0.8026,
            'OXT': -0.8026
        },
        'PRO': {
            'N': -0.2802,
            'CD': 0.0434,
            'HD2': 0.0331,
            'HD3': 0.0331,
            'CG': 0.0466,
            'HG2': 0.0172,
            'HG3': 0.0172,
            'CB': -0.0543,
            'HB2': 0.0381,
            'HB3': 0.0381,
            'CA': -0.1336,
            'HA': 0.0776,
            'C': 0.6631,
            'O': -0.7697,
            'OXT': -0.7697
        },
        'SER': {
            'N': -0.3821,
            'H': 0.2681,
            'CA': -0.2722,
            'HA': 0.1304,
            'CB': 0.1123,
            'HB2': 0.0813,
            'HB3': 0.0813,
            'OG': -0.6514,
            'HG': 0.4474,
            'C': 0.8113,
            'O': -0.8132,
            'OXT': -0.8132
        },
        'THR': {
            'N': -0.3821,
            'H': 0.2681,
            'CA': -0.242,
            'HA': 0.1207,
            'CB': 0.3025,
            'HB': 0.0078,
            'CG2': -0.1853,
            'HG21': 0.0586,
            'HG22': 0.0586,
            'HG23': 0.0586,
            'OG1': -0.6496,
            'HG1': 0.4119,
            'C': 0.781,
            'O': -0.8044,
            'OXT': -0.8044
        },
        'TRP': {
            'N': -0.3821,
            'H': 0.2681,
            'CA': -0.2084,
            'HA': 0.1272,
            'CB': -0.0742,
            'HB2': 0.0497,
            'HB3': 0.0497,
            'CG': -0.0796,
            'CD1': -0.1808,
            'HD1': 0.2043,
            'NE1': -0.3316,
            'HE1': 0.3413,
            'CE2': 0.1222,
            'CZ2': -0.2594,
            'HZ2': 0.1567,
            'CH2': -0.102,
            'HH2': 0.1401,
            'CZ3': -0.2287,
            'HZ3': 0.1507,
            'CE3': -0.1837,
            'HE3': 0.1491,
            'CD2': 0.1078,
            'C': 0.7658,
            'O': -0.8011,
            'OXT': -0.8011
        },
        'TYR': {
            'N': -0.3821,
            'H': 0.2681,
            'CA': -0.2015,
            'HA': 0.1092,
            'CB': -0.0752,
            'HB2': 0.049,
            'HB3': 0.049,
            'CG': 0.0243,
            'CD1': -0.1922,
            'HD1': 0.178,
            'CE1': -0.2458,
            'HE1': 0.1673,
            'CZ': 0.3395,
            'OH': -0.5643,
            'HH': 0.4017,
            'CE2': -0.2458,
            'HE2': 0.1673,
            'CD2': -0.1922,
            'HD2': 0.178,
            'C': 0.7817,
            'O': -0.807,
            'OXT': -0.807
        },
        'VAL': {
            'N': -0.3821,
            'H': 0.2681,
            'CA': -0.3438,
            'HA': 0.1438,
            'CB': 0.194,
            'HB': 0.0308,
            'CG1': -0.3064,
            'HG11': 0.0836,
            'HG12': 0.0836,
            'HG13': 0.0836,
            'CG2': -0.3064,
            'HG21': 0.0836,
            'HG22': 0.0836,
            'HG23': 0.0836,
            'C': 0.835,
            'O': -0.8173,
            'OXT': -0.8173
        },
        'NHE': {
            'N': -0.463,
            'HN1': 0.2315,
            'HN2': 0.2315
        },
        'NME': {
            'N': -0.4157,
            'H': 0.2719,
            'C': -0.149,
            'H1': 0.0976,
            'H2': 0.0976,
            'H3': 0.0976
        }
    },
}
"""dict() that maps three-letter amino-acid codes to their atomic charge (in their C-ter form) based on
different force fields (the 1st key). CAA and WAT This map includes residues of different titration states."""

RESIDUE_CHARGE_MAP_NTERMINAL = {
    "ff19sb" : {
        'ACE': {
            'H1': 0.1123,
            'CH3': -0.3662,
            'H2': 0.1123,
            'H3': 0.1123,
            'C': 0.5972,
            'O': -0.5679
        },
        'ALA': {
            'N': 0.1414,
            'H1': 0.1997,
            'H2': 0.1997,
            'H3': 0.1997,
            'CA': 0.0962,
            'HA': 0.0889,
            'CB': -0.0597,
            'HB1': 0.03,
            'HB2': 0.03,
            'HB3': 0.03,
            'C': 0.6163,
            'O': -0.5722
        },
        'ARG': {
            'N': 0.1305,
            'H1': 0.2083,
            'H2': 0.2083,
            'H3': 0.2083,
            'CA': -0.0223,
            'HA': 0.1242,
            'CB': 0.0118,
            'HB2': 0.0226,
            'HB3': 0.0226,
            'CG': 0.0236,
            'HG2': 0.0309,
            'HG3': 0.0309,
            'CD': 0.0935,
            'HD2': 0.0527,
            'HD3': 0.0527,
            'NE': -0.565,
            'HE': 0.3592,
            'CZ': 0.8281,
            'NH1': -0.8693,
            'HH11': 0.4494,
            'HH12': 0.4494,
            'NH2': -0.8693,
            'HH21': 0.4494,
            'HH22': 0.4494,
            'C': 0.7214,
            'O': -0.6013
        },
        'ASN': {
            'N': 0.1801,
            'H1': 0.1921,
            'H2': 0.1921,
            'H3': 0.1921,
            'CA': 0.0368,
            'HA': 0.1231,
            'CB': -0.0283,
            'HB2': 0.0515,
            'HB3': 0.0515,
            'CG': 0.5833,
            'OD1': -0.5744,
            'ND2': -0.8634,
            'HD21': 0.4097,
            'HD22': 0.4097,
            'C': 0.6163,
            'O': -0.5722
        },
        'ASP': {
            'N': 0.0782,
            'H1': 0.22,
            'H2': 0.22,
            'H3': 0.22,
            'CA': 0.0292,
            'HA': 0.1141,
            'CB': -0.0235,
            'HB2': -0.0169,
            'HB3': -0.0169,
            'CG': 0.8194,
            'OD1': -0.8084,
            'OD2': -0.8084,
            'C': 0.5621,
            'O': -0.5889
        },
        'CYS': {
            'N': 0.1325,
            'H1': 0.2023,
            'H2': 0.2023,
            'H3': 0.2023,
            'CA': 0.0927,
            'HA': 0.1411,
            'CB': -0.1195,
            'HB2': 0.1188,
            'HB3': 0.1188,
            'SG': -0.3298,
            'HG': 0.1975,
            'C': 0.6123,
            'O': -0.5713
        },
        'CYX': {
            'N': 0.2069,
            'H1': 0.1815,
            'H2': 0.1815,
            'H3': 0.1815,
            'CA': 0.1055,
            'HA': 0.0922,
            'CB': -0.0277,
            'HB2': 0.068,
            'HB3': 0.068,
            'SG': -0.0984,
            'C': 0.6123,
            'O': -0.5713
        },
        'GLN': {
            'N': 0.1493,
            'H1': 0.1996,
            'H2': 0.1996,
            'H3': 0.1996,
            'CA': 0.0536,
            'HA': 0.1015,
            'CB': 0.0651,
            'HB2': 0.005,
            'HB3': 0.005,
            'CG': -0.0903,
            'HG2': 0.0331,
            'HG3': 0.0331,
            'CD': 0.7354,
            'OE1': -0.6133,
            'NE2': -1.0031,
            'HE21': 0.4429,
            'HE22': 0.4429,
            'C': 0.6123,
            'O': -0.5713
        },
        'GLU': {
            'N': 0.0017,
            'H1': 0.2391,
            'H2': 0.2391,
            'H3': 0.2391,
            'CA': 0.0588,
            'HA': 0.1202,
            'CB': 0.0909,
            'HB2': -0.0232,
            'HB3': -0.0232,
            'CG': -0.0236,
            'HG2': -0.0315,
            'HG3': -0.0315,
            'CD': 0.8087,
            'OE1': -0.8189,
            'OE2': -0.8189,
            'C': 0.5621,
            'O': -0.5889
        },
        'GLY': {
            'N': 0.2943,
            'H1': 0.1642,
            'H2': 0.1642,
            'H3': 0.1642,
            'CA': -0.01,
            'HA2': 0.0895,
            'HA3': 0.0895,
            'C': 0.6163,
            'O': -0.5722
        },
        'HID': {
            'N': 0.1542,
            'H1': 0.1963,
            'H2': 0.1963,
            'H3': 0.1963,
            'CA': 0.0964,
            'HA': 0.0958,
            'CB': 0.0259,
            'HB2': 0.0209,
            'HB3': 0.0209,
            'CG': -0.0399,
            'ND1': -0.3819,
            'HD1': 0.3632,
            'CE1': 0.2127,
            'HE1': 0.1385,
            'NE2': -0.5711,
            'CD2': 0.1046,
            'HD2': 0.1299,
            'C': 0.6123,
            'O': -0.5713
        },
        'HIE': {
            'N': 0.1472,
            'H1': 0.2016,
            'H2': 0.2016,
            'H3': 0.2016,
            'CA': 0.0236,
            'HA': 0.138,
            'CB': 0.0489,
            'HB2': 0.0223,
            'HB3': 0.0223,
            'CG': 0.174,
            'ND1': -0.5579,
            'CE1': 0.1804,
            'HE1': 0.1397,
            'NE2': -0.2781,
            'HE2': 0.3324,
            'CD2': -0.2349,
            'HD2': 0.1963,
            'C': 0.6123,
            'O': -0.5713
        },
        'HIP': {
            'N': 0.256,
            'H1': 0.1704,
            'H2': 0.1704,
            'H3': 0.1704,
            'CA': 0.0581,
            'HA': 0.1047,
            'CB': 0.0484,
            'HB2': 0.0531,
            'HB3': 0.0531,
            'CG': -0.0236,
            'ND1': -0.151,
            'HD1': 0.3821,
            'CE1': -0.0011,
            'HE1': 0.2645,
            'NE2': -0.1739,
            'HE2': 0.3921,
            'CD2': -0.1433,
            'HD2': 0.2495,
            'C': 0.7214,
            'O': -0.6013
        },
        'ILE': {
            'N': 0.0311,
            'H1': 0.2329,
            'H2': 0.2329,
            'H3': 0.2329,
            'CA': 0.0257,
            'HA': 0.1031,
            'CB': 0.1885,
            'HB': 0.0213,
            'CG2': -0.372,
            'HG21': 0.0947,
            'HG22': 0.0947,
            'HG23': 0.0947,
            'CG1': -0.0387,
            'HG12': 0.0201,
            'HG13': 0.0201,
            'CD1': -0.0908,
            'HD11': 0.0226,
            'HD12': 0.0226,
            'HD13': 0.0226,
            'C': 0.6123,
            'O': -0.5713
        },
        'LEU': {
            'N': 0.101,
            'H1': 0.2148,
            'H2': 0.2148,
            'H3': 0.2148,
            'CA': 0.0104,
            'HA': 0.1053,
            'CB': -0.0244,
            'HB2': 0.0256,
            'HB3': 0.0256,
            'CG': 0.3421,
            'HG': -0.038,
            'CD1': -0.4106,
            'HD11': 0.098,
            'HD12': 0.098,
            'HD13': 0.098,
            'CD2': -0.4104,
            'HD21': 0.098,
            'HD22': 0.098,
            'HD23': 0.098,
            'C': 0.6123,
            'O': -0.5713
        },
        'LYS': {
            'N': 0.0966,
            'H1': 0.2165,
            'H2': 0.2165,
            'H3': 0.2165,
            'CA': -0.0015,
            'HA': 0.118,
            'CB': 0.0212,
            'HB2': 0.0283,
            'HB3': 0.0283,
            'CG': -0.0048,
            'HG2': 0.0121,
            'HG3': 0.0121,
            'CD': -0.0608,
            'HD2': 0.0633,
            'HD3': 0.0633,
            'CE': -0.0181,
            'HE2': 0.1171,
            'HE3': 0.1171,
            'NZ': -0.3764,
            'HZ1': 0.3382,
            'HZ2': 0.3382,
            'HZ3': 0.3382,
            'C': 0.7214,
            'O': -0.6013
        },
        'MET': {
            'N': 0.1592,
            'H1': 0.1984,
            'H2': 0.1984,
            'H3': 0.1984,
            'CA': 0.0221,
            'HA': 0.1116,
            'CB': 0.0865,
            'HB2': 0.0125,
            'HB3': 0.0125,
            'CG': 0.0334,
            'HG2': 0.0292,
            'HG3': 0.0292,
            'SD': -0.2774,
            'CE': -0.0341,
            'HE1': 0.0597,
            'HE2': 0.0597,
            'HE3': 0.0597,
            'C': 0.6123,
            'O': -0.5713
        },
        'PHE': {
            'N': 0.1737,
            'H1': 0.1921,
            'H2': 0.1921,
            'H3': 0.1921,
            'CA': 0.0733,
            'HA': 0.1041,
            'CB': 0.033,
            'HB2': 0.0104,
            'HB3': 0.0104,
            'CG': 0.0031,
            'CD1': -0.1392,
            'HD1': 0.1374,
            'CE1': -0.1602,
            'HE1': 0.1433,
            'CZ': -0.1208,
            'HZ': 0.1329,
            'CE2': -0.1603,
            'HE2': 0.1433,
            'CD2': -0.1391,
            'HD2': 0.1374,
            'C': 0.6123,
            'O': -0.5713
        },
        'PRO': {
            'N': -0.202,
            'H2': 0.312,
            'H3': 0.312,
            'CD': -0.012,
            'HD2': 0.1,
            'HD3': 0.1,
            'CG': -0.121,
            'HG2': 0.1,
            'HG3': 0.1,
            'CB': -0.115,
            'HB2': 0.1,
            'HB3': 0.1,
            'CA': 0.1,
            'HA': 0.1,
            'C': 0.526,
            'O': -0.5,
            'HNN':0.26 #TODO(CJ): check

        },
        'SER': {
            'N': 0.1849,
            'H1': 0.1898,
            'H2': 0.1898,
            'H3': 0.1898,
            'CA': 0.0567,
            'HA': 0.0782,
            'CB': 0.2596,
            'HB2': 0.0273,
            'HB3': 0.0273,
            'OG': -0.6714,
            'HG': 0.4239,
            'C': 0.6163,
            'O': -0.5722
        },
        'THR': {
            'N': 0.1812,
            'H1': 0.1934,
            'H2': 0.1934,
            'H3': 0.1934,
            'CA': 0.0034,
            'HA': 0.1087,
            'CB': 0.4514,
            'HB': -0.0323,
            'CG2': -0.2554,
            'HG21': 0.0627,
            'HG22': 0.0627,
            'HG23': 0.0627,
            'OG1': -0.6764,
            'HG1': 0.407,
            'C': 0.6163,
            'O': -0.5722
        },
        'TRP': {
            'N': 0.1913,
            'H1': 0.1888,
            'H2': 0.1888,
            'H3': 0.1888,
            'CA': 0.0421,
            'HA': 0.1162,
            'CB': 0.0543,
            'HB2': 0.0222,
            'HB3': 0.0222,
            'CG': -0.1654,
            'CD1': -0.1788,
            'HD1': 0.2195,
            'NE1': -0.3444,
            'HE1': 0.3412,
            'CE2': 0.1575,
            'CZ2': -0.271,
            'HZ2': 0.1589,
            'CH2': -0.108,
            'HH2': 0.1411,
            'CZ3': -0.2034,
            'HZ3': 0.1458,
            'CE3': -0.2265,
            'HE3': 0.1646,
            'CD2': 0.1132,
            'C': 0.6123,
            'O': -0.5713
        },
        'TYR': {
            'N': 0.194,
            'H1': 0.1873,
            'H2': 0.1873,
            'H3': 0.1873,
            'CA': 0.057,
            'HA': 0.0983,
            'CB': 0.0659,
            'HB2': 0.0102,
            'HB3': 0.0102,
            'CG': -0.0205,
            'CD1': -0.2002,
            'HD1': 0.172,
            'CE1': -0.2239,
            'HE1': 0.165,
            'CZ': 0.3139,
            'OH': -0.5578,
            'HH': 0.4001,
            'CE2': -0.2239,
            'HE2': 0.165,
            'CD2': -0.2002,
            'HD2': 0.172,
            'C': 0.6123,
            'O': -0.5713
        },
        'VAL': {
            'N': 0.0577,
            'H1': 0.2272,
            'H2': 0.2272,
            'H3': 0.2272,
            'CA': -0.0054,
            'HA': 0.1093,
            'CB': 0.3196,
            'HB': -0.0221,
            'CG1': -0.3129,
            'HG11': 0.0735,
            'HG12': 0.0735,
            'HG13': 0.0735,
            'CG2': -0.3129,
            'HG21': 0.0735,
            'HG22': 0.0735,
            'HG23': 0.0735,
            'C': 0.6163,
            'O': -0.5722
        }
    },
}
"""dict() that maps three-letter amino-acid codes to their atomic charge (in their N-ter form) based on
different force fields (the 1st key). CAA and WAT This map includes residues of different titration states."""

DEPROTONATION_MAPPER: Dict[str, Union[tuple, None]] = {
    "ASH": {"OD2": ("ASP", "HD2")},
    "CYS": {"SG": ("CYM", "HG")},
    "GLH": {"OE2": ("GLU", "HE2")},
    "HIP": {"ND1": ("HIE", "HD1"),"NE2": ("HID", "HE2")},
    "HID": {"ND1": ("HIE", "HD1")},  # note these are just switching
    "HIE": {"NE2": ("HID", "HE2")},  # note these are just switching
    "LYS": {"NZ": ("LYN", "HZ1")},
    "TYR": {"OH": ("TYM", "HH")},
    "ARG": {"NH2": ("AR0", "HH22"),"NH1": ("AR0", "HH12")}
}  # note this need to switch name after depro
"""a map of residue name of deprotonatable residues. This means the residue have ambiguous protonation state with a pH
around 7.0. The map is presented in the way that the deprotonatable residue is the key and its
target_atom : (deprotoned state, deprotoned atom) is the value. In the file, these residue name are arranged with each
charge state as an indent from +1 to -1.
{resi_name : {deprotonated_atom_name : (depro_resi_name, depro_proton_name), ...}
See /resource/ProtonationState.cdx for more detail"""

NOPROTON_LIST = ["ASP", "GLU", "MET"]
"""a list of residue name with no acidic proton"""

RESIDUE_NON_MUTATE_ATOM_MAPPER: Dict[str, List[str]] = {
    "default" : ["N", "H", "CA", "HA", "CB", "C", "O"],
    "PRO" : ['N','CA','HA','CB','C','O'],
    "GLY" : ['N','H','CA','C','O'],
}
"""a dictionary of atom names that won't change in a subsitution-mutation. Bascially mainchain+CB.
The key is the residue after the mutation."""

# yapf: enable

def convert_to_three_letter(one_letter: str) -> str:
    """Converts a one letter amino acid name to a three letter. If supplied code is invalid, raises an enzy_htp.core.InvalidResidueCode() exception."""
    if len(one_letter) != 1:
        raise InvalidResidueCode(f"expecting one letter residue code. '{one_letter}' is invalid")
    one_letter = one_letter.upper()
    result = ONE_LETTER_AA_MAPPER.get(one_letter, None)
    if not result:
        raise InvalidResidueCode(f"Invalid residue code {one_letter}")
    return result


def convert_to_canonical_three_letter(three_letter: str) -> str:
    """Converts a one letter amino acid name to a three letter. If supplied code is invalid, raises an enzy_htp.core.InvalidResidueCode() exception."""
    if len(three_letter) != 3:
        raise InvalidResidueCode(f"expecting three letter residue code. '{three_letter}' is invalid")
    three_letter = three_letter.upper()
    result = THREE_TO_THREE_LETTER_CAA_MAPPER.get(three_letter, None)
    if not result:
        raise InvalidResidueCode(f"Invalid residue code {three_letter}")
    return result


def convert_to_one_letter(three_letter: str) -> str:
    """Converts a threee letter amino acid name to a one letter. If supplied code is invalid, raises an enzy_htp.core.InvalidResidueCode() exception."""
    if len(three_letter) != 3:
        raise InvalidResidueCode(f"expecting three letter residue code. '{three_letter}' is invalid")
    three_letter = three_letter.upper()
    result = THREE_LETTER_AA_MAPPER.get(three_letter, None)
    if not result:
        raise InvalidResidueCode(f"Invalid residue code {three_letter}")
    return result


def get_element_aliases(ff: str, element: str) -> Set[str]:
    """Gets all element aliases for a given force field (ff) and element name, retungin in a set. If the ff is not supported, will log and exit."""
    if ff not in RESIDUE_ELEMENT_MAP:
        _LOGGER.error(f"{ff} is not a supported force field type. Allowed are '{', '.join(list(RESIDUE_ELEMENT_MAP.keys()))}'. Exiting...")
        exit(0)
    ff_dict = RESIDUE_ELEMENT_MAP[ff]
    aliases = []
    for alias, elem in ff_dict.items():
        if elem == element:
            aliases.append(alias)

    return set(aliases)


def one_letters_except(existing: str) -> List[str]:
    """Creates a list of all one letter amino acid codes. Case insensitive. If an invalid code is supplied, an enzy_htp.core.InvalidResidueCode() error is thrown."""
    existing = existing.upper()
    if existing not in ONE_LETTER_AA_MAPPER:
        raise InvalidResidueCode(f"{existing} is not a valid one letter amino acid")
    result = list(set(list(ONE_LETTER_AA_MAPPER.keys())))
    return list(filter(lambda s: s != existing, result))


def residue_polarity(code: str) -> str:
    """Determines the polarity of a one-letter nucleotide, being 'negative', 'neutral' or 'positive."""
    if len(code) != 1:
        raise InvalidResidueCode(f"expecting one letter residue code. '{code}' is invalid")

    result: str() = "unknown"
    for ptype in "positive negative neutral".split():
        if code in RESIDUE_CATEGORIES[ptype]:
            result = ptype
    return result


def non_polar(code: str) -> bool:
    # TODO(CJ): should probably check if it is a valid one letter residue code
    """Determines if a one-letter nucleotide amino acid is non-polar. Returns True if it is non-polar."""
    if len(code) != 1:
        raise InvalidResidueCode(f"expecting one letter residue code. '{code}' is invalid")

    return code in RESIDUE_CATEGORIES["nonpolar"]


def polar(code: str) -> bool:
    """Determines if a one-letter nucleotide amino acid is polar. Returns True if it is non-polar."""
    # TODO(CJ): should probably check if it is a valid one letter residue code
    return not non_polar(code)


def get_non_mutate_atom_names(residue_name: str) -> List[str]:
    """Get names of atoms that does not involve in a substitution mutation to
    the residue ({residue_name}). 
    For example: for mutating to most residues, all
    the side chain atoms will be replaced whiled the main chain atoms and CB won't
    change. So in this case, the returning list of atoms are the mainchain atoms and
    CB. For mutating to GLY, CB and HA are also removed so the list may change
    depending on the {residue_name}.
    This function is mainly used for mutate_stru_with_tleap().
    Args:
        residue_name: the 3-letter name for the residue after the mutation
    Returns:
        a list of atom names that remains the same before and after mutation"""
    if len(residue_name) != 3:
        raise InvalidResidueCode(f"expecting three letter residue code. '{residue_name}' is invalid")
    residue_name = residue_name.upper()
    result = RESIDUE_NON_MUTATE_ATOM_MAPPER.get(residue_name, RESIDUE_NON_MUTATE_ATOM_MAPPER["default"])

    return result
